package ui;

import java.awt.event.*;
import domain.examiner;
import javax.swing.JOptionPane;
import control.MaintainExaminationSystem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;
import domain.admin;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tommy
 */
public class createExaminer extends javax.swing.JPanel {

    /**
     * Creates new form createExaminer
     */
    public createExaminer() {
        System.out.println("createExaminer are begin executed");
        initComponents();
        ArrayList<String> courseList = new ArrayList<String>();
        for(int i=0;i<maintainExamSys.getCourseList().size();i++){
            courseList.add(maintainExamSys.getCourseList().get(i).getcourseName());
        }
        String[] courseArr = new String[courseList.size()];
        courseArr = courseList.toArray(courseArr);
        jcb_examiner_course.setModel(new javax.swing.DefaultComboBoxModel(courseArr));
        jtf_examiner_studentID.setDocument(new JTextFieldLimit(5));
        jtf_examiner_MyKad_back.setDocument(new JTextFieldLimit(4));
        jtf_examiner_MyKad_front.setDocument(new JTextFieldLimit(6));
        jtf_examiner_MyKad_middle.setDocument(new JTextFieldLimit(2));
        jtf_examiner_age.setDocument(new JTextFieldLimit(2));
        jtf_examiner_contactNum_back.setDocument(new JTextFieldLimit(7));
        jtf_examiner_contactNum_front.setDocument(new JTextFieldLimit(3));
        jtf_examiner_name.setDocument(new JTextFieldLimit(30));
        System.out.println("createExaminer executed successfully");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        createExaminerPanel_leftPanel = new javax.swing.JPanel();
        createExaminerPanel_text_Create = new java.awt.Label();
        createExaminerPanel_text_Record = new java.awt.Label();
        createExaminerPanel_text_Examiner = new java.awt.Label();
        createExaminerPanel_rightPanel = new javax.swing.JPanel();
        createExaminerPanel_text_Name = new java.awt.Label();
        createExaminerPanel_text_helpTxt1 = new java.awt.Label();
        createExaminerPanel_text_Intake_year = new java.awt.Label();
        createExaminerPanel_text_Programme = new java.awt.Label();
        jbt_resetField = new javax.swing.JButton();
        jbt_createExaminer = new javax.swing.JButton();
        jcb_examiner_intakeYear = new javax.swing.JComboBox<>();
        jtf_examiner_studentID = new javax.swing.JTextField();
        jtf_examiner_name = new javax.swing.JTextField();
        createExaminerPanel_text_Age = new java.awt.Label();
        jtf_examiner_age = new javax.swing.JTextField();
        createExaminerPanel_text_Student_ID = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        createExaminerPanel_text_staff_myKadNumber = new java.awt.Label();
        createExaminerPanel_text_Contact_number = new java.awt.Label();
        jtf_examiner_contactNum_front = new javax.swing.JTextField();
        jcb_examiner_course = new javax.swing.JComboBox<>();
        jtf_examiner_MyKad_back = new javax.swing.JTextField();
        createExaminerPanel_text_helpTxt3 = new java.awt.Label();
        jtf_examiner_MyKad_front = new javax.swing.JTextField();
        createExaminerPanel_text_helpTxt4 = new java.awt.Label();
        jtf_examiner_MyKad_middle = new javax.swing.JTextField();
        createExaminerPanel_text_helpTxt5 = new java.awt.Label();
        jtf_examiner_contactNum_back = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));

        createExaminerPanel_leftPanel.setBackground(new java.awt.Color(204, 204, 255));
        createExaminerPanel_leftPanel.setToolTipText("");

        createExaminerPanel_text_Create.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        createExaminerPanel_text_Create.setText("Create");

        createExaminerPanel_text_Record.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        createExaminerPanel_text_Record.setText("Record");

        createExaminerPanel_text_Examiner.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        createExaminerPanel_text_Examiner.setText("Examiner");

        javax.swing.GroupLayout createExaminerPanel_leftPanelLayout = new javax.swing.GroupLayout(createExaminerPanel_leftPanel);
        createExaminerPanel_leftPanel.setLayout(createExaminerPanel_leftPanelLayout);
        createExaminerPanel_leftPanelLayout.setHorizontalGroup(
            createExaminerPanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createExaminerPanel_leftPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(createExaminerPanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createExaminerPanel_text_Create, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createExaminerPanel_text_Examiner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createExaminerPanel_text_Record, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        createExaminerPanel_leftPanelLayout.setVerticalGroup(
            createExaminerPanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createExaminerPanel_leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createExaminerPanel_text_Create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createExaminerPanel_text_Examiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createExaminerPanel_text_Record, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        createExaminerPanel_rightPanel.setBackground(new java.awt.Color(204, 255, 204));
        createExaminerPanel_rightPanel.setToolTipText("");

        createExaminerPanel_text_Name.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createExaminerPanel_text_Name.setText("Name");

        createExaminerPanel_text_helpTxt1.setFont(new java.awt.Font("FangSong", 1, 14)); // NOI18N
        createExaminerPanel_text_helpTxt1.setText("(Last 5 digit only)");

        createExaminerPanel_text_Intake_year.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createExaminerPanel_text_Intake_year.setText("Intake year");

        createExaminerPanel_text_Programme.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createExaminerPanel_text_Programme.setText("Course");

        jbt_resetField.setBackground(new java.awt.Color(255, 204, 153));
        jbt_resetField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_resetField.setText("Reset");
        jbt_resetField.setToolTipText("Click to reset all fields");
        jbt_resetField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_resetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_resetFieldActionPerformed(evt);
            }
        });

        jbt_createExaminer.setBackground(new java.awt.Color(255, 204, 153));
        jbt_createExaminer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_createExaminer.setText("Create");
        jbt_createExaminer.setToolTipText("Click to create record");
        jbt_createExaminer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_createExaminer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_createExaminerActionPerformed(evt);
            }
        });

        jcb_examiner_intakeYear.setBackground(new java.awt.Color(153, 255, 153));
        jcb_examiner_intakeYear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcb_examiner_intakeYear.setModel(new javax.swing.DefaultComboBoxModel(new Integer[]{new java.util.Date().getYear()+1900,new java.util.Date().getYear()+1899,new java.util.Date().getYear()+1898,new java.util.Date().getYear()+1897,new java.util.Date().getYear()+1896,new java.util.Date().getYear()+1895}));
        jcb_examiner_intakeYear.setToolTipText("Choose examiner's intake year");

        jtf_examiner_studentID.setBackground(new java.awt.Color(204, 204, 255));
        jtf_examiner_studentID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_examiner_studentID.setToolTipText("Enter examiner's student ID here");
        jtf_examiner_studentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_examiner_studentIDKeyTyped(evt);
            }
        });

        jtf_examiner_name.setBackground(new java.awt.Color(204, 204, 255));
        jtf_examiner_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_examiner_name.setToolTipText("Enter examiner's name here");
        jtf_examiner_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_examiner_nameActionPerformed(evt);
            }
        });

        createExaminerPanel_text_Age.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createExaminerPanel_text_Age.setText("Age");

        jtf_examiner_age.setEditable(false);
        jtf_examiner_age.setBackground(new java.awt.Color(204, 204, 255));
        jtf_examiner_age.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_examiner_age.setToolTipText("Enter examiner's age here");
        jtf_examiner_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_examiner_ageActionPerformed(evt);
            }
        });
        jtf_examiner_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_examiner_ageKeyTyped(evt);
            }
        });

        createExaminerPanel_text_Student_ID.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createExaminerPanel_text_Student_ID.setText("Student ID");

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setToolTipText("Bonjour");

        jLabel2.setToolTipText("Bonjour");

        createExaminerPanel_text_staff_myKadNumber.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createExaminerPanel_text_staff_myKadNumber.setText("MyKad number");

        createExaminerPanel_text_Contact_number.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createExaminerPanel_text_Contact_number.setText("Contact number");

        jtf_examiner_contactNum_front.setBackground(new java.awt.Color(204, 204, 255));
        jtf_examiner_contactNum_front.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_examiner_contactNum_front.setToolTipText("Enter examiner's contact number");
        jtf_examiner_contactNum_front.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_examiner_contactNum_frontKeyTyped(evt);
            }
        });

        jcb_examiner_course.setBackground(new java.awt.Color(153, 255, 153));
        jcb_examiner_course.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcb_examiner_course.setModel(jcb_examiner_course.getModel());
        jcb_examiner_course.setToolTipText("Choose examiner's course");
        jcb_examiner_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_examiner_courseActionPerformed(evt);
            }
        });

        jtf_examiner_MyKad_back.setBackground(new java.awt.Color(204, 204, 255));
        jtf_examiner_MyKad_back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_examiner_MyKad_back.setToolTipText("Enter examiner's MyKad number");
        jtf_examiner_MyKad_back.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_examiner_MyKad_backKeyTyped(evt);
            }
        });

        createExaminerPanel_text_helpTxt3.setFont(new java.awt.Font("FangSong", 1, 14)); // NOI18N
        createExaminerPanel_text_helpTxt3.setText("-");

        jtf_examiner_MyKad_front.setBackground(new java.awt.Color(204, 204, 255));
        jtf_examiner_MyKad_front.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_examiner_MyKad_front.setToolTipText("Enter examiner's MyKad number");
        jtf_examiner_MyKad_front.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_examiner_MyKad_frontKeyTyped(evt);
            }
        });

        createExaminerPanel_text_helpTxt4.setFont(new java.awt.Font("FangSong", 1, 14)); // NOI18N
        createExaminerPanel_text_helpTxt4.setText("-");

        jtf_examiner_MyKad_middle.setBackground(new java.awt.Color(204, 204, 255));
        jtf_examiner_MyKad_middle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_examiner_MyKad_middle.setToolTipText("Enter examiner's MyKad number");
        jtf_examiner_MyKad_middle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_examiner_MyKad_middleKeyTyped(evt);
            }
        });

        createExaminerPanel_text_helpTxt5.setFont(new java.awt.Font("FangSong", 1, 14)); // NOI18N
        createExaminerPanel_text_helpTxt5.setText("-");

        jtf_examiner_contactNum_back.setBackground(new java.awt.Color(204, 204, 255));
        jtf_examiner_contactNum_back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_examiner_contactNum_back.setToolTipText("Enter examiner's contact number");
        jtf_examiner_contactNum_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_examiner_contactNum_backActionPerformed(evt);
            }
        });
        jtf_examiner_contactNum_back.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_examiner_contactNum_backKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout createExaminerPanel_rightPanelLayout = new javax.swing.GroupLayout(createExaminerPanel_rightPanel);
        createExaminerPanel_rightPanel.setLayout(createExaminerPanel_rightPanelLayout);
        createExaminerPanel_rightPanelLayout.setHorizontalGroup(
            createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbt_createExaminer, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jbt_resetField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createExaminerPanel_text_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createExaminerPanel_text_Programme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createExaminerPanel_text_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createExaminerPanel_text_Student_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createExaminerPanel_text_staff_myKadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createExaminerPanel_text_Intake_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createExaminerPanel_text_Contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcb_examiner_intakeYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_examiner_age, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_examiner_name, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                        .addComponent(jtf_examiner_studentID, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(createExaminerPanel_text_helpTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jcb_examiner_course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                        .addComponent(jtf_examiner_MyKad_front, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(createExaminerPanel_text_helpTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(jtf_examiner_MyKad_middle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(createExaminerPanel_text_helpTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                        .addComponent(jtf_examiner_contactNum_front, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(createExaminerPanel_text_helpTxt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_examiner_contactNum_back, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_examiner_MyKad_back, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 291, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        createExaminerPanel_rightPanelLayout.setVerticalGroup(
            createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createExaminerPanel_text_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_examiner_name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(createExaminerPanel_text_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jtf_examiner_age, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_examiner_studentID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createExaminerPanel_text_helpTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createExaminerPanel_text_Student_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createExaminerPanel_text_Programme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_examiner_course, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createExaminerPanel_text_staff_myKadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(createExaminerPanel_text_helpTxt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtf_examiner_MyKad_front, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                    .addComponent(jtf_examiner_MyKad_middle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createExaminerPanel_text_helpTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_examiner_MyKad_back, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel1))))
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createExaminerPanel_text_Intake_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb_examiner_intakeYear, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(createExaminerPanel_text_Contact_number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_examiner_contactNum_front)
                            .addComponent(createExaminerPanel_text_helpTxt5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_examiner_contactNum_back, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(207, 207, 207)
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_resetField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_createExaminer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(createExaminerPanel_leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createExaminerPanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createExaminerPanel_leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(createExaminerPanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_resetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_resetFieldActionPerformed
        // TODO add your handling code here:
        int isConfirmed = 0;
        isConfirmed = JOptionPane.showConfirmDialog(jtf_examiner_MyKad_back, "Are you sure you want to clear all fields?", "CLEAR FIELD CONFIRMATION", HEIGHT);
        if(isConfirmed==0){
            jtf_examiner_name.setText("");
            jtf_examiner_age.setText("");
            jtf_examiner_MyKad_front.setText("");
            jtf_examiner_MyKad_middle.setText("");
            jtf_examiner_MyKad_back.setText("");
            jtf_examiner_studentID.setText("");
            jtf_examiner_contactNum_front.setText("");
            jtf_examiner_contactNum_back.setText("");
            jcb_examiner_intakeYear.setSelectedIndex(0);
            jcb_examiner_course.setSelectedIndex(0);
        }
        else{}
    }//GEN-LAST:event_jbt_resetFieldActionPerformed

    private void jbt_createExaminerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_createExaminerActionPerformed
        // TODO add your handling code here:
        if(jtf_examiner_contactNum_front.getText().length()==3&&jtf_examiner_name.getText().isEmpty()==false&&jtf_examiner_MyKad_back.getText().length()==4&&jtf_examiner_MyKad_front.getText().length()==6&&jtf_examiner_MyKad_middle.getText().length()==2&&jtf_examiner_studentID.getText().length()==5&&jtf_examiner_contactNum_back.getText().length()==7){
                examiner examiner = new examiner();
                examiner.setexaminerName(jtf_examiner_name.getText());
                examiner.setexaminerIC_front(jtf_examiner_MyKad_front.getText());
                examiner.setexaminerIC_middle(jtf_examiner_MyKad_middle.getText());
                examiner.setexaminerIC_back(jtf_examiner_MyKad_back.getText());
                examiner.setexaminerIntakeYear(Integer.parseInt(String.valueOf(jcb_examiner_intakeYear.getSelectedItem())));
                examiner.setexaminerCourse(String.valueOf(jcb_examiner_course.getSelectedItem()));
                examiner.setexaminerBalance(0.00);
                examiner.setexaminerPassword(jtf_examiner_MyKad_front.getText());
                examiner.setexaminerAnswer("");
                examiner.setexaminerID(jtf_examiner_studentID.getText());
                examiner.setexaminerContactNumber_front(jtf_examiner_contactNum_front.getText());
                examiner.setexaminerContactNumber_back(jtf_examiner_contactNum_back.getText());
                examiner.setexaminerContactNumber();
                examiner.setexaminerIC();
                //calculate age
                String year = jtf_examiner_MyKad_front.getText();
                int userBornYear = 0;
                if(year.charAt(0)=='9'||year.charAt(0)=='8'){
                    userBornYear  = 1900+Integer.parseInt(String.valueOf(year.charAt(0)))*10+Integer.parseInt(String.valueOf(year.charAt(1)));
                }
                else if(year.charAt(0)=='0'){
                    userBornYear  = 2000+Integer.parseInt(String.valueOf(year.charAt(0)))*10+Integer.parseInt(String.valueOf(year.charAt(1)));
                }
                int currentYear = new java.util.Date().getYear()+1900;
                int age = currentYear-userBornYear;
                jtf_examiner_age.setText(String.valueOf(age));
                examiner.setexaminerAge(age);
                int userBornMonth = Integer.parseInt(String.valueOf(examiner.getexaminerIC_front().charAt(2)))*10+Integer.parseInt(String.valueOf(examiner.getexaminerIC_front().charAt(3)));
                int userBornday = Integer.parseInt(String.valueOf(examiner.getexaminerIC_front().charAt(4)))*10+Integer.parseInt(String.valueOf(examiner.getexaminerIC_front().charAt(5)));
                if(userBornYear>=1980&&userBornMonth>=1&&userBornMonth<=12&&userBornday<=31&&userBornday>=1){
                    if(examiner.getexaminerContactNumber_front().charAt(0)=='0'&&examiner.getexaminerContactNumber_front().charAt(1)=='1'){
                        if(JOptionPane.showConfirmDialog(null, "Are you sure you want to create this record with the following information:\nExaminer ID: "+examiner.getexaminerID()+"\nName: "+examiner.getexaminerName()+"\nAge: "+examiner.getexaminerAge()+"\nContact number: "+examiner.getexaminerContactNumber()+"\nMyKad number: "+examiner.getexaminerIC()+"\nIntake year "+examiner.getexaminerIntakeYear()+"\nCourse: "+examiner.getexaminerCourse(), "CREATE RECORD CONFIRMATION", HEIGHT)==0){
                    maintainExamSys.createExaminer(examiner);
                }
                else
                    JOptionPane.showMessageDialog(null, "Create record fail!", "CREATE RECORD FAIL", HEIGHT);
                    }
                    else
                        JOptionPane.showMessageDialog(null, "Your phone number format is incorrect! (Tips: Phone number format: 01x-xxxxxxx)!", "CREATE RECORD FAIL", HEIGHT);
                }
                else
                    JOptionPane.showMessageDialog(null, "Your MyKad number is not accepted due to error born date, please kindly refer your original MyKad number!", "CREATE RECORD FAIL", HEIGHT);
                
        }
        else
            JOptionPane.showMessageDialog(null, "Create record fail! Please fill in all form before you decide to create record.", "CREATE RECORD FAIL", HEIGHT);
    }//GEN-LAST:event_jbt_createExaminerActionPerformed

  
    private void jtf_examiner_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_examiner_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_examiner_ageActionPerformed

    private void jtf_examiner_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_examiner_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_examiner_nameActionPerformed

    private void jtf_examiner_contactNum_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_examiner_contactNum_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_examiner_contactNum_backActionPerformed

    private void jcb_examiner_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_examiner_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_examiner_courseActionPerformed

    private void jtf_examiner_studentIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_examiner_studentIDKeyTyped
       // TODO add your handling code here:
       char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)){
           evt.consume();
           java.awt.Toolkit.getDefaultToolkit().beep();
       }
    }//GEN-LAST:event_jtf_examiner_studentIDKeyTyped

    private void jtf_examiner_MyKad_frontKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_examiner_MyKad_frontKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)){
           evt.consume();
           java.awt.Toolkit.getDefaultToolkit().beep();
       }
    }//GEN-LAST:event_jtf_examiner_MyKad_frontKeyTyped

    private void jtf_examiner_MyKad_middleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_examiner_MyKad_middleKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)){
           evt.consume();
           java.awt.Toolkit.getDefaultToolkit().beep();
       }
    }//GEN-LAST:event_jtf_examiner_MyKad_middleKeyTyped

    private void jtf_examiner_MyKad_backKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_examiner_MyKad_backKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)){
           evt.consume();
           java.awt.Toolkit.getDefaultToolkit().beep();
       }
    }//GEN-LAST:event_jtf_examiner_MyKad_backKeyTyped

    private void jtf_examiner_contactNum_frontKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_examiner_contactNum_frontKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)){
           evt.consume();
           java.awt.Toolkit.getDefaultToolkit().beep();
       }
    }//GEN-LAST:event_jtf_examiner_contactNum_frontKeyTyped

    private void jtf_examiner_contactNum_backKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_examiner_contactNum_backKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)){
           evt.consume();
           java.awt.Toolkit.getDefaultToolkit().beep();
       }
    }//GEN-LAST:event_jtf_examiner_contactNum_backKeyTyped

    private void jtf_examiner_ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_examiner_ageKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_examiner_ageKeyTyped

    public class JTextFieldLimit extends PlainDocument {
        private int limit;
        JTextFieldLimit(int limit) {
            super();
            this.limit = limit;
        }
        public void insertString( int offset, String  str, AttributeSet attr ) throws BadLocationException {
            if (str == null) return;
            
            if ((getLength() + str.length()) <= limit) {
                super.insertString(offset, str, attr);
            }
        }
    }


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel createExaminerPanel_leftPanel;
    private javax.swing.JPanel createExaminerPanel_rightPanel;
    private java.awt.Label createExaminerPanel_text_Age;
    private java.awt.Label createExaminerPanel_text_Contact_number;
    private java.awt.Label createExaminerPanel_text_Create;
    private java.awt.Label createExaminerPanel_text_Examiner;
    private java.awt.Label createExaminerPanel_text_Intake_year;
    private java.awt.Label createExaminerPanel_text_Name;
    private java.awt.Label createExaminerPanel_text_Programme;
    private java.awt.Label createExaminerPanel_text_Record;
    private java.awt.Label createExaminerPanel_text_Student_ID;
    private java.awt.Label createExaminerPanel_text_helpTxt1;
    private java.awt.Label createExaminerPanel_text_helpTxt3;
    private java.awt.Label createExaminerPanel_text_helpTxt4;
    private java.awt.Label createExaminerPanel_text_helpTxt5;
    private java.awt.Label createExaminerPanel_text_staff_myKadNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbt_createExaminer;
    private javax.swing.JButton jbt_resetField;
    private javax.swing.JComboBox<String> jcb_examiner_course;
    private javax.swing.JComboBox<String> jcb_examiner_intakeYear;
    private javax.swing.JTextField jtf_examiner_MyKad_back;
    private javax.swing.JTextField jtf_examiner_MyKad_front;
    private javax.swing.JTextField jtf_examiner_MyKad_middle;
    private javax.swing.JTextField jtf_examiner_age;
    private javax.swing.JTextField jtf_examiner_contactNum_back;
    private javax.swing.JTextField jtf_examiner_contactNum_front;
    private javax.swing.JTextField jtf_examiner_name;
    private javax.swing.JTextField jtf_examiner_studentID;
    // End of variables declaration//GEN-END:variables
    MaintainExaminationSystem maintainExamSys = new MaintainExaminationSystem();
    private boolean isInteger=false;
}
