package ui;

import java.awt.event.*;
import domain.subject;
import javax.swing.JOptionPane;
import control.MaintainExaminationSystem;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;
import domain.admin;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tommy
 */
public class createSubject extends javax.swing.JPanel {

    /**
     * Creates new form createExaminer
     */
    public createSubject() {
        initComponents();
        ArrayList<String> courseList = new ArrayList<String>();
        for(int i=0;i<maintainExamSys.getCourseList().size();i++){
            courseList.add(maintainExamSys.getCourseList().get(i).getcourseID());
        }
        String[] courseArr = new String[courseList.size()];
        courseArr = courseList.toArray(courseArr);
        jcb_subject_course.setModel(new javax.swing.DefaultComboBoxModel(courseArr));
        jtf_subject_subjectID.setDocument(new JTextFieldLimit(5));
        jtf_subject_name.setDocument(new JTextFieldLimit(30));
        jtf_subject_lecturer.setDocument(new JTextFieldLimit(30));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        createSubjectPanel_leftPanel = new javax.swing.JPanel();
        createSubjectPanel_text_Create = new java.awt.Label();
        createSubjectPanel_text_Record = new java.awt.Label();
        createSubjectPanel_text_Staff = new java.awt.Label();
        createSubjectPanel_rightPanel = new javax.swing.JPanel();
        createSubjectPanel_text_Subject = new java.awt.Label();
        createExaminerPanel_text_helpTxt1 = new java.awt.Label();
        createSubjectPanel_text_Course = new java.awt.Label();
        jbt_resetField = new javax.swing.JButton();
        jbt_createSubject = new javax.swing.JButton();
        jtf_subject_subjectID = new javax.swing.JTextField();
        jtf_subject_name = new javax.swing.JTextField();
        createSubjectPanel_text_subject_ID = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        createSubjectPanel_text_description = new java.awt.Label();
        jcb_subject_course = new javax.swing.JComboBox<>();
        createSubjectPanel_text_Lecturer = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_subjectDescription = new javax.swing.JTextArea();
        jtf_subject_lecturer = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));

        createSubjectPanel_leftPanel.setBackground(new java.awt.Color(204, 204, 255));
        createSubjectPanel_leftPanel.setToolTipText("");

        createSubjectPanel_text_Create.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        createSubjectPanel_text_Create.setText("Create");

        createSubjectPanel_text_Record.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        createSubjectPanel_text_Record.setText("Record");

        createSubjectPanel_text_Staff.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        createSubjectPanel_text_Staff.setText("Subject");

        javax.swing.GroupLayout createSubjectPanel_leftPanelLayout = new javax.swing.GroupLayout(createSubjectPanel_leftPanel);
        createSubjectPanel_leftPanel.setLayout(createSubjectPanel_leftPanelLayout);
        createSubjectPanel_leftPanelLayout.setHorizontalGroup(
            createSubjectPanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createSubjectPanel_leftPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(createSubjectPanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createSubjectPanel_text_Create, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createSubjectPanel_text_Staff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createSubjectPanel_text_Record, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        createSubjectPanel_leftPanelLayout.setVerticalGroup(
            createSubjectPanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createSubjectPanel_leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createSubjectPanel_text_Create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createSubjectPanel_text_Staff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createSubjectPanel_text_Record, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        createSubjectPanel_rightPanel.setBackground(new java.awt.Color(204, 255, 204));
        createSubjectPanel_rightPanel.setToolTipText("");

        createSubjectPanel_text_Subject.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createSubjectPanel_text_Subject.setText("Subject");

        createExaminerPanel_text_helpTxt1.setFont(new java.awt.Font("FangSong", 1, 14)); // NOI18N
        createExaminerPanel_text_helpTxt1.setText("(Last 5 digit only)");

        createSubjectPanel_text_Course.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createSubjectPanel_text_Course.setText("Course");

        jbt_resetField.setBackground(new java.awt.Color(255, 204, 153));
        jbt_resetField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_resetField.setText("Reset");
        jbt_resetField.setToolTipText("Click to reset all fields");
        jbt_resetField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_resetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_resetFieldActionPerformed(evt);
            }
        });

        jbt_createSubject.setBackground(new java.awt.Color(255, 204, 153));
        jbt_createSubject.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_createSubject.setText("Create");
        jbt_createSubject.setToolTipText("Click to create record");
        jbt_createSubject.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_createSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_createSubjectActionPerformed(evt);
            }
        });

        jtf_subject_subjectID.setBackground(new java.awt.Color(204, 204, 255));
        jtf_subject_subjectID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_subject_subjectID.setToolTipText("Enter examiner's student ID here");
        jtf_subject_subjectID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_subject_subjectIDKeyTyped(evt);
            }
        });

        jtf_subject_name.setBackground(new java.awt.Color(204, 204, 255));
        jtf_subject_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_subject_name.setToolTipText("Enter examiner's name here");
        jtf_subject_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_subject_nameActionPerformed(evt);
            }
        });

        createSubjectPanel_text_subject_ID.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createSubjectPanel_text_subject_ID.setText("Subject ID");

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setToolTipText("Bonjour");

        jLabel2.setToolTipText("Bonjour");

        createSubjectPanel_text_description.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createSubjectPanel_text_description.setText("Description");

        jcb_subject_course.setBackground(new java.awt.Color(153, 255, 153));
        jcb_subject_course.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcb_subject_course.setModel(jcb_subject_course.getModel());
        jcb_subject_course.setToolTipText("Choose examiner's course");
        jcb_subject_course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_subject_courseActionPerformed(evt);
            }
        });

        createSubjectPanel_text_Lecturer.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createSubjectPanel_text_Lecturer.setText("Lecturer");

        jta_subjectDescription.setBackground(new java.awt.Color(204, 204, 255));
        jta_subjectDescription.setColumns(20);
        jta_subjectDescription.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jta_subjectDescription.setRows(5);
        jScrollPane1.setViewportView(jta_subjectDescription);

        jtf_subject_lecturer.setBackground(new java.awt.Color(204, 204, 255));
        jtf_subject_lecturer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_subject_lecturer.setToolTipText("Enter examiner's student ID here");
        jtf_subject_lecturer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_subject_lecturerKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout createSubjectPanel_rightPanelLayout = new javax.swing.GroupLayout(createSubjectPanel_rightPanel);
        createSubjectPanel_rightPanel.setLayout(createSubjectPanel_rightPanelLayout);
        createSubjectPanel_rightPanelLayout.setHorizontalGroup(
            createSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createSubjectPanel_rightPanelLayout.createSequentialGroup()
                .addGroup(createSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createSubjectPanel_rightPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(createSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createSubjectPanel_rightPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbt_createSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jbt_resetField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createSubjectPanel_rightPanelLayout.createSequentialGroup()
                                .addComponent(createSubjectPanel_text_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(createSubjectPanel_rightPanelLayout.createSequentialGroup()
                                .addGroup(createSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createSubjectPanel_text_Subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createSubjectPanel_text_Course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createSubjectPanel_text_subject_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(createSubjectPanel_text_Lecturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 766, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, createSubjectPanel_rightPanelLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(createSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createSubjectPanel_rightPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(createSubjectPanel_rightPanelLayout.createSequentialGroup()
                                .addGroup(createSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcb_subject_course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(createSubjectPanel_rightPanelLayout.createSequentialGroup()
                                        .addComponent(jtf_subject_subjectID, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(createExaminerPanel_text_helpTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtf_subject_name, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                    .addComponent(jtf_subject_lecturer))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        createSubjectPanel_rightPanelLayout.setVerticalGroup(
            createSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createSubjectPanel_rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createSubjectPanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(createSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createSubjectPanel_text_Subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_subject_name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(createSubjectPanel_text_subject_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(createExaminerPanel_text_helpTxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtf_subject_subjectID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcb_subject_course, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(createSubjectPanel_text_Course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(createSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createSubjectPanel_text_Lecturer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_subject_lecturer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createSubjectPanel_rightPanelLayout.createSequentialGroup()
                        .addComponent(createSubjectPanel_text_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(createSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createSubjectPanel_rightPanelLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createSubjectPanel_rightPanelLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel1)))
                        .addGap(207, 207, 207)
                        .addGroup(createSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbt_resetField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbt_createSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(createSubjectPanel_leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createSubjectPanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createSubjectPanel_leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(createSubjectPanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_resetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_resetFieldActionPerformed
        // TODO add your handling code here:
        int isConfirmed = 0;
        isConfirmed = JOptionPane.showConfirmDialog(null, "Are you sure you want to clear all fields?", "CLEAR FIELD CONFIRMATION", HEIGHT);
        if(isConfirmed==0){
            jtf_subject_name.setText("");
            jtf_subject_subjectID.setText("");
            jcb_subject_course.setSelectedIndex(0);
            jtf_subject_lecturer.setText("");
            jta_subjectDescription.setText("");
        }
        else{}
    }//GEN-LAST:event_jbt_resetFieldActionPerformed

    private void jbt_createSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_createSubjectActionPerformed
        // TODO add your handling code here:
        if(jtf_subject_name.getText().isEmpty()==false&&jtf_subject_subjectID.getText().length()==5&&jta_subjectDescription.getText().isEmpty()==false&&jtf_subject_lecturer.getText().isEmpty()==false){
                subject subject = new subject();
                subject.setSubjectName(jtf_subject_name.getText());
                subject.setCourseID(String.valueOf(jcb_subject_course.getSelectedItem()));
                subject.setSubjectID(jtf_subject_subjectID.getText());
                subject.setSubjectDescription(jta_subjectDescription.getText());
                subject.setLecturer(jtf_subject_lecturer.getText());
                subject.setCourseName(maintainExamSys.getCourseNameByCourseID(subject.getCourseID()));
                subject.setPassRate(0);
                subject.setTotalExaminer(0);
                if(JOptionPane.showConfirmDialog(null, "Are you sure you want to create this record with the following information:\nSubject ID: "+subject.getSubjectID()+"\nName: "+subject.getSubjectName()+"\nSubject description: "+subject.getSubjectDescription()+"\nCourse ID: "+subject.getCourseID()+"\nLecturer: "+subject.getLecturer(), "CREATE RECORD CONFIRMATION", HEIGHT)==0){
                    maintainExamSys.createSubject(subject);
                }
                else
                    JOptionPane.showMessageDialog(null, "Create record fail!", "CREATE RECORD FAIL", HEIGHT);
                
        }
        else
            JOptionPane.showMessageDialog(null, "Create record fail! Please fill in all form before you decide to create record.", "CREATE RECORD FAIL", HEIGHT);
    }//GEN-LAST:event_jbt_createSubjectActionPerformed

  
    private void jtf_subject_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_subject_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_subject_nameActionPerformed

    private void jcb_subject_courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_subject_courseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_subject_courseActionPerformed

    private void jtf_subject_subjectIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_subject_subjectIDKeyTyped
       // TODO add your handling code here:
       char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c== KeyEvent.VK_DELETE)){
           evt.consume();
           java.awt.Toolkit.getDefaultToolkit().beep();
       }
    }//GEN-LAST:event_jtf_subject_subjectIDKeyTyped

    private void jtf_subject_lecturerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_subject_lecturerKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_subject_lecturerKeyTyped

    public class JTextFieldLimit extends PlainDocument {
        private int limit;
        JTextFieldLimit(int limit) {
            super();
            this.limit = limit;
        }
        public void insertString( int offset, String  str, AttributeSet attr ) throws BadLocationException {
            if (str == null) return;
            
            if ((getLength() + str.length()) <= limit) {
                super.insertString(offset, str, attr);
            }
        }
    }


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private java.awt.Label createExaminerPanel_text_helpTxt1;
    private javax.swing.JPanel createSubjectPanel_leftPanel;
    private javax.swing.JPanel createSubjectPanel_rightPanel;
    private java.awt.Label createSubjectPanel_text_Course;
    private java.awt.Label createSubjectPanel_text_Create;
    private java.awt.Label createSubjectPanel_text_Lecturer;
    private java.awt.Label createSubjectPanel_text_Record;
    private java.awt.Label createSubjectPanel_text_Staff;
    private java.awt.Label createSubjectPanel_text_Subject;
    private java.awt.Label createSubjectPanel_text_description;
    private java.awt.Label createSubjectPanel_text_subject_ID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_createSubject;
    private javax.swing.JButton jbt_resetField;
    private javax.swing.JComboBox<String> jcb_subject_course;
    private javax.swing.JTextArea jta_subjectDescription;
    private javax.swing.JTextField jtf_subject_lecturer;
    private javax.swing.JTextField jtf_subject_name;
    private javax.swing.JTextField jtf_subject_subjectID;
    // End of variables declaration//GEN-END:variables
    MaintainExaminationSystem maintainExamSys = new MaintainExaminationSystem();
    private boolean isInteger=false;
}
