package ui;

import control.MaintainExaminationSystem;
import javax.swing.JOptionPane;
import domain.timetable;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tommy
 */
public class createTimetable extends javax.swing.JPanel {

    /**
     * Creates new form createExaminer
     */
    public createTimetable() {
        initComponents();
        ArrayList<String> courseList = new ArrayList<String>();
        for(int i=0;i<maintainExamSys.getCourseList().size();i++){
            courseList.add(maintainExamSys.getCourseList().get(i).getcourseName());
        }
        String[] courseArr = new String[courseList.size()];
        courseArr = courseList.toArray(courseArr);
        jcb_timetable_course.setModel(new javax.swing.DefaultComboBoxModel(courseArr));
        jtf_timetable_timetableName.setDocument(new JTextFieldLimit(30));
        jcb_timetable_course.setEditable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        createTimetablePanel_leftPanel = new javax.swing.JPanel();
        createTimetablePanel_text_Create = new java.awt.Label();
        createTimetablePanel_text_Timetable = new java.awt.Label();
        createTimetablePanel_rightPanel = new javax.swing.JPanel();
        jbt_createExaminer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf_timetable_timetableName = new javax.swing.JTextField();
        createTimetablePanel_text_Timetable_name = new java.awt.Label();
        jcb_timetable_course = new javax.swing.JComboBox<>();
        createTimetablePanel_text_Course = new java.awt.Label();

        setBackground(new java.awt.Color(0, 0, 0));

        createTimetablePanel_leftPanel.setBackground(new java.awt.Color(204, 204, 255));
        createTimetablePanel_leftPanel.setToolTipText("");

        createTimetablePanel_text_Create.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        createTimetablePanel_text_Create.setText("Create");

        createTimetablePanel_text_Timetable.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        createTimetablePanel_text_Timetable.setText("Timetable");

        javax.swing.GroupLayout createTimetablePanel_leftPanelLayout = new javax.swing.GroupLayout(createTimetablePanel_leftPanel);
        createTimetablePanel_leftPanel.setLayout(createTimetablePanel_leftPanelLayout);
        createTimetablePanel_leftPanelLayout.setHorizontalGroup(
            createTimetablePanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createTimetablePanel_leftPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(createTimetablePanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createTimetablePanel_text_Create, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createTimetablePanel_text_Timetable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        createTimetablePanel_leftPanelLayout.setVerticalGroup(
            createTimetablePanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createTimetablePanel_leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createTimetablePanel_text_Create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createTimetablePanel_text_Timetable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        createTimetablePanel_rightPanel.setBackground(new java.awt.Color(204, 255, 204));
        createTimetablePanel_rightPanel.setToolTipText("");

        jbt_createExaminer.setBackground(new java.awt.Color(255, 204, 153));
        jbt_createExaminer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_createExaminer.setText("Create");
        jbt_createExaminer.setToolTipText("Click to create record");
        jbt_createExaminer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_createExaminer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_createExaminerActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setToolTipText("Bonjour");

        jLabel2.setToolTipText("Bonjour");

        jtf_timetable_timetableName.setBackground(new java.awt.Color(204, 204, 255));
        jtf_timetable_timetableName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_timetable_timetableName.setToolTipText("Enter examiner's MyKad number");
        jtf_timetable_timetableName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_timetable_timetableNameKeyTyped(evt);
            }
        });

        createTimetablePanel_text_Timetable_name.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createTimetablePanel_text_Timetable_name.setText("Timetable name");

        jcb_timetable_course.setBackground(new java.awt.Color(153, 255, 153));
        jcb_timetable_course.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcb_timetable_course.setModel(jcb_timetable_course.getModel());

        createTimetablePanel_text_Course.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createTimetablePanel_text_Course.setText("Course");

        javax.swing.GroupLayout createTimetablePanel_rightPanelLayout = new javax.swing.GroupLayout(createTimetablePanel_rightPanel);
        createTimetablePanel_rightPanel.setLayout(createTimetablePanel_rightPanelLayout);
        createTimetablePanel_rightPanelLayout.setHorizontalGroup(
            createTimetablePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createTimetablePanel_rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createTimetablePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createTimetablePanel_text_Course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createTimetablePanel_text_Timetable_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(createTimetablePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtf_timetable_timetableName)
                    .addComponent(jcb_timetable_course, 0, 364, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createTimetablePanel_rightPanelLayout.createSequentialGroup()
                .addGap(600, 792, Short.MAX_VALUE)
                .addGroup(createTimetablePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createTimetablePanel_rightPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createTimetablePanel_rightPanelLayout.createSequentialGroup()
                        .addComponent(jbt_createExaminer, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        createTimetablePanel_rightPanelLayout.setVerticalGroup(
            createTimetablePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createTimetablePanel_rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createTimetablePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createTimetablePanel_text_Timetable_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_timetable_timetableName, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createTimetablePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createTimetablePanel_rightPanelLayout.createSequentialGroup()
                        .addGap(0, 173, Short.MAX_VALUE)
                        .addGroup(createTimetablePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createTimetablePanel_rightPanelLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createTimetablePanel_rightPanelLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel1)))
                        .addGap(207, 207, 207)
                        .addComponent(jbt_createExaminer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(createTimetablePanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(createTimetablePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jcb_timetable_course)
                            .addComponent(createTimetablePanel_text_Course, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(createTimetablePanel_leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createTimetablePanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createTimetablePanel_leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(createTimetablePanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_createExaminerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_createExaminerActionPerformed
        // TODO add your handling code here:
        if(jtf_timetable_timetableName.getText().isEmpty()==false){
            JFrame frm = new JFrame("Edit Timetable");
            frm.add(new editTimetable(jtf_timetable_timetableName.getText(), String.valueOf(jcb_timetable_course.getSelectedItem()), frm));
        frm.setTitle("Edit timetable");
        frm.setSize(1280, 720);
        frm.setLocationRelativeTo(null);
        frm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frm.setVisible(true);
        frm.setResizable(true);
        }
        else
        JOptionPane.showMessageDialog(null, "Create timetable fail! Please fill in the timetable name before you decide to create a timetable.", "CREATE TIMETABLE FAIL", HEIGHT);
    }//GEN-LAST:event_jbt_createExaminerActionPerformed

    public void closeFrame(JFrame frame){
        frame.dispose();
    }
    
    private void jtf_timetable_timetableNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_timetable_timetableNameKeyTyped

    }//GEN-LAST:event_jtf_timetable_timetableNameKeyTyped

  
    public class JTextFieldLimit extends PlainDocument {
        private int limit;
        JTextFieldLimit(int limit) {
            super();
            this.limit = limit;
        }
        public void insertString( int offset, String  str, AttributeSet attr ) throws BadLocationException {
            if (str == null) return;
            
            if ((getLength() + str.length()) <= limit) {
                super.insertString(offset, str, attr);
            }
        }
    }


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel createTimetablePanel_leftPanel;
    private javax.swing.JPanel createTimetablePanel_rightPanel;
    private java.awt.Label createTimetablePanel_text_Course;
    private java.awt.Label createTimetablePanel_text_Create;
    private java.awt.Label createTimetablePanel_text_Timetable;
    private java.awt.Label createTimetablePanel_text_Timetable_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbt_createExaminer;
    private javax.swing.JComboBox<String> jcb_timetable_course;
    private javax.swing.JTextField jtf_timetable_timetableName;
    // End of variables declaration//GEN-END:variables

    MaintainExaminationSystem maintainExamSys = new MaintainExaminationSystem();
}
