package ui;

import java.awt.event.*;
import domain.examiner;
import javax.swing.JOptionPane;
import control.MaintainExaminationSystem;
import domain.staff;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tommy
 */
public class createStaff extends javax.swing.JPanel {

    /**
     * Creates new form createExaminer
     */
    public createStaff() {
        initComponents();
        jtf_staff_ID.setDocument(new JTextFieldLimit(5));
        jtf_staff_MyKad_back.setDocument(new JTextFieldLimit(4));
        jtf_staff_MyKad_front.setDocument(new JTextFieldLimit(6));
        jtf_staff_MyKad_middle.setDocument(new JTextFieldLimit(2));
        jtf_staff_age.setDocument(new JTextFieldLimit(2));
        jtf_staff_contactNum_back.setDocument(new JTextFieldLimit(7));
        jtf_staff_contactNum_front.setDocument(new JTextFieldLimit(3));
        jtf_staff_name.setDocument(new JTextFieldLimit(30));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        createStaffPanel_leftPanel = new javax.swing.JPanel();
        createStaffPanel_text_Create = new java.awt.Label();
        createStaffPanel_text_Record = new java.awt.Label();
        createStaffPanel_text_Examiner = new java.awt.Label();
        createStaffPanel_rightPanel = new javax.swing.JPanel();
        createStaffPanel_text_Name = new java.awt.Label();
        createExaminerPanel_text_helpTxt1 = new java.awt.Label();
        jbt_resetField = new javax.swing.JButton();
        jbt_createExaminer = new javax.swing.JButton();
        jtf_staff_ID = new javax.swing.JTextField();
        jtf_staff_name = new javax.swing.JTextField();
        createStaffPanel_text_Age = new java.awt.Label();
        jtf_staff_age = new javax.swing.JTextField();
        createStaffPanel_text_Staff_ID = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        createStaffPanel_text_staff_myKadNumber = new java.awt.Label();
        createStaffPanell_text_Contact_number = new java.awt.Label();
        jtf_staff_contactNum_front = new javax.swing.JTextField();
        jtf_staff_MyKad_back = new javax.swing.JTextField();
        createExaminerPanel_text_helpTxt3 = new java.awt.Label();
        jtf_staff_MyKad_front = new javax.swing.JTextField();
        createExaminerPanel_text_helpTxt4 = new java.awt.Label();
        jtf_staff_MyKad_middle = new javax.swing.JTextField();
        createExaminerPanel_text_helpTxt5 = new java.awt.Label();
        jtf_staff_contactNum_back = new javax.swing.JTextField();
        createStaffPanell_text_Address = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_staff_address = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 0, 0));

        createStaffPanel_leftPanel.setBackground(new java.awt.Color(204, 204, 255));
        createStaffPanel_leftPanel.setToolTipText("");

        createStaffPanel_text_Create.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        createStaffPanel_text_Create.setText("Create");

        createStaffPanel_text_Record.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        createStaffPanel_text_Record.setText("Record");

        createStaffPanel_text_Examiner.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        createStaffPanel_text_Examiner.setText("Staff");

        javax.swing.GroupLayout createStaffPanel_leftPanelLayout = new javax.swing.GroupLayout(createStaffPanel_leftPanel);
        createStaffPanel_leftPanel.setLayout(createStaffPanel_leftPanelLayout);
        createStaffPanel_leftPanelLayout.setHorizontalGroup(
            createStaffPanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createStaffPanel_leftPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(createStaffPanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createStaffPanel_text_Create, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createStaffPanel_text_Examiner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createStaffPanel_text_Record, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        createStaffPanel_leftPanelLayout.setVerticalGroup(
            createStaffPanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createStaffPanel_leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createStaffPanel_text_Create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createStaffPanel_text_Examiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createStaffPanel_text_Record, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        createStaffPanel_rightPanel.setBackground(new java.awt.Color(204, 255, 204));
        createStaffPanel_rightPanel.setToolTipText("");

        createStaffPanel_text_Name.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createStaffPanel_text_Name.setText("Name");

        createExaminerPanel_text_helpTxt1.setFont(new java.awt.Font("FangSong", 1, 14)); // NOI18N
        createExaminerPanel_text_helpTxt1.setText("(Last 5 digit only)");

        jbt_resetField.setBackground(new java.awt.Color(255, 204, 153));
        jbt_resetField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_resetField.setText("Reset");
        jbt_resetField.setToolTipText("Click to reset all fields");
        jbt_resetField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_resetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_resetFieldActionPerformed(evt);
            }
        });

        jbt_createExaminer.setBackground(new java.awt.Color(255, 204, 153));
        jbt_createExaminer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_createExaminer.setText("Create");
        jbt_createExaminer.setToolTipText("Click to create record");
        jbt_createExaminer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_createExaminer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_createExaminerActionPerformed(evt);
            }
        });

        jtf_staff_ID.setBackground(new java.awt.Color(204, 204, 255));
        jtf_staff_ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_staff_ID.setToolTipText("Enter examiner's student ID here");
        jtf_staff_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_staff_IDKeyTyped(evt);
            }
        });

        jtf_staff_name.setBackground(new java.awt.Color(204, 204, 255));
        jtf_staff_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_staff_name.setToolTipText("Enter examiner's name here");
        jtf_staff_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_staff_nameActionPerformed(evt);
            }
        });

        createStaffPanel_text_Age.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createStaffPanel_text_Age.setText("Age");

        jtf_staff_age.setEditable(false);
        jtf_staff_age.setBackground(new java.awt.Color(204, 204, 255));
        jtf_staff_age.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_staff_age.setToolTipText("Enter examiner's age here");
        jtf_staff_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_staff_ageActionPerformed(evt);
            }
        });
        jtf_staff_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_staff_ageKeyTyped(evt);
            }
        });

        createStaffPanel_text_Staff_ID.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createStaffPanel_text_Staff_ID.setText("Staff ID");

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setToolTipText("Bonjour");

        jLabel2.setToolTipText("Bonjour");

        createStaffPanel_text_staff_myKadNumber.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createStaffPanel_text_staff_myKadNumber.setText("MyKad number");

        createStaffPanell_text_Contact_number.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createStaffPanell_text_Contact_number.setText("Contact number");

        jtf_staff_contactNum_front.setBackground(new java.awt.Color(204, 204, 255));
        jtf_staff_contactNum_front.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_staff_contactNum_front.setToolTipText("Enter examiner's contact number");
        jtf_staff_contactNum_front.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_staff_contactNum_frontKeyTyped(evt);
            }
        });

        jtf_staff_MyKad_back.setBackground(new java.awt.Color(204, 204, 255));
        jtf_staff_MyKad_back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_staff_MyKad_back.setToolTipText("Enter examiner's MyKad number");
        jtf_staff_MyKad_back.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_staff_MyKad_backKeyTyped(evt);
            }
        });

        createExaminerPanel_text_helpTxt3.setFont(new java.awt.Font("FangSong", 1, 14)); // NOI18N
        createExaminerPanel_text_helpTxt3.setText("-");

        jtf_staff_MyKad_front.setBackground(new java.awt.Color(204, 204, 255));
        jtf_staff_MyKad_front.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_staff_MyKad_front.setToolTipText("Enter examiner's MyKad number");
        jtf_staff_MyKad_front.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_staff_MyKad_frontKeyTyped(evt);
            }
        });

        createExaminerPanel_text_helpTxt4.setFont(new java.awt.Font("FangSong", 1, 14)); // NOI18N
        createExaminerPanel_text_helpTxt4.setText("-");

        jtf_staff_MyKad_middle.setBackground(new java.awt.Color(204, 204, 255));
        jtf_staff_MyKad_middle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_staff_MyKad_middle.setToolTipText("Enter examiner's MyKad number");
        jtf_staff_MyKad_middle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_staff_MyKad_middleKeyTyped(evt);
            }
        });

        createExaminerPanel_text_helpTxt5.setFont(new java.awt.Font("FangSong", 1, 14)); // NOI18N
        createExaminerPanel_text_helpTxt5.setText("-");

        jtf_staff_contactNum_back.setBackground(new java.awt.Color(204, 204, 255));
        jtf_staff_contactNum_back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_staff_contactNum_back.setToolTipText("Enter examiner's contact number");
        jtf_staff_contactNum_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_staff_contactNum_backActionPerformed(evt);
            }
        });
        jtf_staff_contactNum_back.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_staff_contactNum_backKeyTyped(evt);
            }
        });

        createStaffPanell_text_Address.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        createStaffPanell_text_Address.setText("Address");

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 255));

        jta_staff_address.setBackground(new java.awt.Color(204, 204, 255));
        jta_staff_address.setColumns(20);
        jta_staff_address.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jta_staff_address.setRows(5);
        jScrollPane1.setViewportView(jta_staff_address);

        javax.swing.GroupLayout createStaffPanel_rightPanelLayout = new javax.swing.GroupLayout(createStaffPanel_rightPanel);
        createStaffPanel_rightPanel.setLayout(createStaffPanel_rightPanelLayout);
        createStaffPanel_rightPanelLayout.setHorizontalGroup(
            createStaffPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createStaffPanel_rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createStaffPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createStaffPanel_rightPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbt_createExaminer, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jbt_resetField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createStaffPanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(createStaffPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createStaffPanel_text_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createStaffPanel_text_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createStaffPanel_text_Staff_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createStaffPanel_text_staff_myKadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createStaffPanell_text_Contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createStaffPanell_text_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(createStaffPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(createStaffPanel_rightPanelLayout.createSequentialGroup()
                                .addComponent(jtf_staff_contactNum_front, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createExaminerPanel_text_helpTxt5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_staff_contactNum_back, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtf_staff_age, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_staff_name, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(createStaffPanel_rightPanelLayout.createSequentialGroup()
                                .addComponent(jtf_staff_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createExaminerPanel_text_helpTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createStaffPanel_rightPanelLayout.createSequentialGroup()
                                .addComponent(jtf_staff_MyKad_front, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createExaminerPanel_text_helpTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_staff_MyKad_middle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createExaminerPanel_text_helpTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_staff_MyKad_back, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addContainerGap())
        );
        createStaffPanel_rightPanelLayout.setVerticalGroup(
            createStaffPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createStaffPanel_rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createStaffPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createStaffPanel_text_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_staff_name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(createStaffPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createStaffPanel_rightPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(createStaffPanel_text_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createStaffPanel_rightPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jtf_staff_age, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createStaffPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtf_staff_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createExaminerPanel_text_helpTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createStaffPanel_text_Staff_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createStaffPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createStaffPanel_text_staff_myKadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_staff_MyKad_front, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createExaminerPanel_text_helpTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_staff_MyKad_middle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createExaminerPanel_text_helpTxt4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_staff_MyKad_back, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createStaffPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createStaffPanel_rightPanelLayout.createSequentialGroup()
                        .addGap(0, 53, Short.MAX_VALUE)
                        .addGroup(createStaffPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createStaffPanel_rightPanelLayout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createStaffPanel_rightPanelLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel1)))
                        .addGap(207, 207, 207)
                        .addGroup(createStaffPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbt_resetField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbt_createExaminer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(createStaffPanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(createStaffPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(createStaffPanell_text_Contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_staff_contactNum_front, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createExaminerPanel_text_helpTxt5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_staff_contactNum_back, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createStaffPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createStaffPanell_text_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(createStaffPanel_leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createStaffPanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createStaffPanel_leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(createStaffPanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_resetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_resetFieldActionPerformed
        // TODO add your handling code here:
        int isConfirmed = 0;
        isConfirmed = JOptionPane.showConfirmDialog(jtf_staff_MyKad_back, "Are you sure you want to clear all fields?", "CLEAR FIELD CONFIRMATION", HEIGHT);
        if(isConfirmed==0){
            jtf_staff_name.setText("");
            jtf_staff_age.setText("");
            jtf_staff_MyKad_front.setText("");
            jtf_staff_MyKad_middle.setText("");
            jtf_staff_MyKad_back.setText("");
            jtf_staff_ID.setText("");
            jtf_staff_contactNum_front.setText("");
            jtf_staff_contactNum_back.setText("");
            jta_staff_address.setText("");
        }
        else{}
    }//GEN-LAST:event_jbt_resetFieldActionPerformed

    private void jbt_createExaminerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_createExaminerActionPerformed
        // TODO add your handling code here:
        if(jtf_staff_contactNum_front.getText().length()==3&&jtf_staff_name.getText().isEmpty()==false&&jtf_staff_MyKad_back.getText().length()==4&&jtf_staff_MyKad_front.getText().length()==6&&jtf_staff_MyKad_middle.getText().length()==2&&jtf_staff_ID.getText().length()==5&&jtf_staff_contactNum_back.getText().length()==7&&jta_staff_address.getText().isEmpty()==false){
                staff staff = new staff();
                staff.setStafName(jtf_staff_name.getText());
                staff.setStaffIC_front(jtf_staff_MyKad_front.getText());
                staff.setStaffIC_middle(jtf_staff_MyKad_middle.getText());
                staff.setStaffIC_back(jtf_staff_MyKad_back.getText());
                staff.setStaffAnswer("");
                staff.setStaffID(jtf_staff_ID.getText());
                staff.setStaffContactNumber_front(jtf_staff_contactNum_front.getText());
                staff.setStaffContactNumber_back(jtf_staff_contactNum_back.getText());
                staff.setStaffContactNumber();
                staff.setStaffIC();
                //calculate age
                String year = jtf_staff_MyKad_front.getText();
                int userBornYear = 0;
                if(year.charAt(0)=='9'||year.charAt(0)=='8'||year.charAt(0)=='7'||year.charAt(0)=='6'){
                    userBornYear  = 1900+Integer.parseInt(String.valueOf(year.charAt(0)))*10+Integer.parseInt(String.valueOf(year.charAt(1)));
                }
                else if(year.charAt(0)=='0'){
                    userBornYear  = 2000+Integer.parseInt(String.valueOf(year.charAt(0)))*10+Integer.parseInt(String.valueOf(year.charAt(1)));
                }
                int currentYear = new java.util.Date().getYear()+1900;
                int age = currentYear-userBornYear;
                jtf_staff_age.setText(String.valueOf(age));
                staff.setStaffAge(age);
                int userBornMonth = Integer.parseInt(String.valueOf(staff.getStaffIC_front().charAt(2)))*10+Integer.parseInt(String.valueOf(staff.getStaffIC_front().charAt(3)));
                int userBornday = Integer.parseInt(String.valueOf(staff.getStaffIC_front().charAt(4)))*10+Integer.parseInt(String.valueOf(staff.getStaffIC_front().charAt(5)));
                staff.setStaffAddress(jta_staff_address.getText());
                if(userBornYear>=1960&&userBornYear<=1996&&userBornMonth>=1&&userBornMonth<=12&&userBornday<=31&&userBornday>=1){
                    if(staff.getStaffContactNumber_front().charAt(0)=='0'&&staff.getStaffContactNumber_front().charAt(1)=='1'){
                        if(JOptionPane.showConfirmDialog(jtf_staff_MyKad_back, "Are you sure you want to create this record with the following information:\nStaff ID: "+staff.getStaffID()+"\nName: "+staff.getSatffName()+"\nAge: "+staff.getStaffAge()+"\nContact number: "+staff.getStaffContactNumber()+"\nMyKad number: "+staff.getStaffIC()+"\nAddress: "+staff.getStaffAddress(), "CREATE RECORD CONFIRMATION", JOptionPane.INFORMATION_MESSAGE)==0){
                    maintainExamSys.createStaff(staff);
                }
                else
                    JOptionPane.showMessageDialog(null, "Create record fail!", "CREATE RECORD FAIL", HEIGHT);
                    }
                    else
                        JOptionPane.showMessageDialog(null, "Your phone number format is incorrect! (Tips: Phone number format: 01x-xxxxxxx)!", "CREATE RECORD FAIL", HEIGHT);
                }
                else
                    JOptionPane.showMessageDialog(null, "Your MyKad number is not accepted due to error born date, please kindly refer your original MyKad number!", "CREATE RECORD FAIL", HEIGHT);
                    
                
        }
        else
            JOptionPane.showMessageDialog(jtf_staff_MyKad_back, "Create record fail! Please fill in all form before you decide to create record.", "CREATE RECORD FAIL", HEIGHT);
    }//GEN-LAST:event_jbt_createExaminerActionPerformed

  
    private void jtf_staff_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_staff_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_staff_ageActionPerformed

    private void jtf_staff_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_staff_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_staff_nameActionPerformed

    private void jtf_staff_contactNum_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_staff_contactNum_backActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_staff_contactNum_backActionPerformed

    private void jtf_staff_IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_staff_IDKeyTyped
       // TODO add your handling code here:
       char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)){
           evt.consume();
           java.awt.Toolkit.getDefaultToolkit().beep();
       }
    }//GEN-LAST:event_jtf_staff_IDKeyTyped

    private void jtf_staff_MyKad_frontKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_staff_MyKad_frontKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)){
           evt.consume();
           java.awt.Toolkit.getDefaultToolkit().beep();
       }
    }//GEN-LAST:event_jtf_staff_MyKad_frontKeyTyped

    private void jtf_staff_MyKad_middleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_staff_MyKad_middleKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)){
           evt.consume();
           java.awt.Toolkit.getDefaultToolkit().beep();
       }
    }//GEN-LAST:event_jtf_staff_MyKad_middleKeyTyped

    private void jtf_staff_MyKad_backKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_staff_MyKad_backKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)){
           evt.consume();
           java.awt.Toolkit.getDefaultToolkit().beep();
       }
    }//GEN-LAST:event_jtf_staff_MyKad_backKeyTyped

    private void jtf_staff_contactNum_frontKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_staff_contactNum_frontKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)){
           evt.consume();
           java.awt.Toolkit.getDefaultToolkit().beep();
       }
    }//GEN-LAST:event_jtf_staff_contactNum_frontKeyTyped

    private void jtf_staff_contactNum_backKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_staff_contactNum_backKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)){
           evt.consume();
           java.awt.Toolkit.getDefaultToolkit().beep();
       }
    }//GEN-LAST:event_jtf_staff_contactNum_backKeyTyped

    private void jtf_staff_ageKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_staff_ageKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_staff_ageKeyTyped

    public class JTextFieldLimit extends PlainDocument {
        private int limit;
        JTextFieldLimit(int limit) {
            super();
            this.limit = limit;
        }
        public void insertString( int offset, String  str, AttributeSet attr ) throws BadLocationException {
            if (str == null) return;
            
            if ((getLength() + str.length()) <= limit) {
                super.insertString(offset, str, attr);
            }
        }
    }


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private java.awt.Label createExaminerPanel_text_helpTxt1;
    private java.awt.Label createExaminerPanel_text_helpTxt3;
    private java.awt.Label createExaminerPanel_text_helpTxt4;
    private java.awt.Label createExaminerPanel_text_helpTxt5;
    private javax.swing.JPanel createStaffPanel_leftPanel;
    private javax.swing.JPanel createStaffPanel_rightPanel;
    private java.awt.Label createStaffPanel_text_Age;
    private java.awt.Label createStaffPanel_text_Create;
    private java.awt.Label createStaffPanel_text_Examiner;
    private java.awt.Label createStaffPanel_text_Name;
    private java.awt.Label createStaffPanel_text_Record;
    private java.awt.Label createStaffPanel_text_Staff_ID;
    private java.awt.Label createStaffPanel_text_staff_myKadNumber;
    private java.awt.Label createStaffPanell_text_Address;
    private java.awt.Label createStaffPanell_text_Contact_number;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_createExaminer;
    private javax.swing.JButton jbt_resetField;
    private javax.swing.JTextArea jta_staff_address;
    private javax.swing.JTextField jtf_staff_ID;
    private javax.swing.JTextField jtf_staff_MyKad_back;
    private javax.swing.JTextField jtf_staff_MyKad_front;
    private javax.swing.JTextField jtf_staff_MyKad_middle;
    private javax.swing.JTextField jtf_staff_age;
    private javax.swing.JTextField jtf_staff_contactNum_back;
    private javax.swing.JTextField jtf_staff_contactNum_front;
    private javax.swing.JTextField jtf_staff_name;
    // End of variables declaration//GEN-END:variables
    MaintainExaminationSystem maintainExamSys = new MaintainExaminationSystem();
    private boolean isInteger=false;
}
