package ui;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import control.MaintainExaminationSystem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tommy
 */
import domain.staff;
public class displayStaff extends javax.swing.JPanel {

    /**
     * Creates new form createExaminer
     */
    private staff staff;
    private JFrame frame;
    private MaintainExaminationSystem maintainExamSys = new MaintainExaminationSystem();
    public displayStaff(staff staff, JFrame frame) {
        initComponents();
        this.frame = frame;
        this.staff = staff;
        jtf_displayName.setText(staff.getSatffName());
        jtf_display_myKadNumber.setText(staff.getStaffIC());
        jtf_displayStaff_ID.setText(staff.getStaffID());
        jtf_displayAge.setText(String.valueOf(staff.getStaffAge()));
        jtf_displayContactNum.setText(staff.getStaffContactNumber());
        System.out.println("staff.getStaffAddress(): "+staff.getStaffAddress());
        jta_displayAddress.setText(staff.getStaffAddress());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        createExaminerPanel_rightPanel = new javax.swing.JPanel();
        displayStaffrPanel_text_Name = new java.awt.Label();
        displayStaffPanel_text_Address = new java.awt.Label();
        jbt_removeExaminer = new javax.swing.JButton();
        jbt_updateExaminer = new javax.swing.JButton();
        displayStaffrPanel_text_Age = new java.awt.Label();
        displayStaffPanel_text_Student_ID = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf_displayStaff_ID = new javax.swing.JTextField();
        jtf_displayName = new javax.swing.JTextField();
        jtf_displayAge = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_displayAddress = new javax.swing.JTextArea();
        displayStaffPanel_text_examiner_myKadNumber = new java.awt.Label();
        jtf_display_myKadNumber = new javax.swing.JTextField();
        displayStaffPanel_text_Contact_number = new java.awt.Label();
        jtf_displayContactNum = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));

        createExaminerPanel_rightPanel.setBackground(new java.awt.Color(204, 255, 204));
        createExaminerPanel_rightPanel.setToolTipText("");

        displayStaffrPanel_text_Name.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayStaffrPanel_text_Name.setText("Name");

        displayStaffPanel_text_Address.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayStaffPanel_text_Address.setText("Address");

        jbt_removeExaminer.setBackground(new java.awt.Color(255, 204, 153));
        jbt_removeExaminer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_removeExaminer.setText("Remove");
        jbt_removeExaminer.setToolTipText("Click to remove record");
        jbt_removeExaminer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_removeExaminer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_removeExaminerActionPerformed(evt);
            }
        });

        jbt_updateExaminer.setBackground(new java.awt.Color(255, 204, 153));
        jbt_updateExaminer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_updateExaminer.setText("Update");
        jbt_updateExaminer.setToolTipText("Click to update record");
        jbt_updateExaminer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_updateExaminer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_updateExaminerActionPerformed(evt);
            }
        });

        displayStaffrPanel_text_Age.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayStaffrPanel_text_Age.setText("Age");

        displayStaffPanel_text_Student_ID.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayStaffPanel_text_Student_ID.setText("Staff ID");

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setToolTipText("Bonjour");

        jLabel2.setToolTipText("Bonjour");

        jtf_displayStaff_ID.setEditable(false);
        jtf_displayStaff_ID.setBackground(new java.awt.Color(204, 204, 255));
        jtf_displayStaff_ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_displayStaff_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_displayStaff_IDActionPerformed(evt);
            }
        });

        jtf_displayName.setEditable(false);
        jtf_displayName.setBackground(new java.awt.Color(204, 204, 255));
        jtf_displayName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_displayName.setToolTipText("");
        jtf_displayName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_displayNameActionPerformed(evt);
            }
        });

        jtf_displayAge.setEditable(false);
        jtf_displayAge.setBackground(new java.awt.Color(204, 204, 255));
        jtf_displayAge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_displayAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_displayAgeActionPerformed(evt);
            }
        });

        jta_displayAddress.setEditable(false);
        jta_displayAddress.setBackground(new java.awt.Color(204, 204, 255));
        jta_displayAddress.setColumns(20);
        jta_displayAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jta_displayAddress.setRows(5);
        jScrollPane1.setViewportView(jta_displayAddress);

        displayStaffPanel_text_examiner_myKadNumber.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayStaffPanel_text_examiner_myKadNumber.setText("myKad number");

        jtf_display_myKadNumber.setEditable(false);
        jtf_display_myKadNumber.setBackground(new java.awt.Color(204, 204, 255));
        jtf_display_myKadNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_display_myKadNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_display_myKadNumberActionPerformed(evt);
            }
        });

        displayStaffPanel_text_Contact_number.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayStaffPanel_text_Contact_number.setText("Contact number");

        jtf_displayContactNum.setEditable(false);
        jtf_displayContactNum.setBackground(new java.awt.Color(204, 204, 255));
        jtf_displayContactNum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_displayContactNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_displayContactNumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createExaminerPanel_rightPanelLayout = new javax.swing.GroupLayout(createExaminerPanel_rightPanel);
        createExaminerPanel_rightPanel.setLayout(createExaminerPanel_rightPanelLayout);
        createExaminerPanel_rightPanelLayout.setHorizontalGroup(
            createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayStaffrPanel_text_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayStaffPanel_text_examiner_myKadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayStaffPanel_text_Student_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel1))
                            .addComponent(displayStaffPanel_text_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtf_displayName, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtf_displayStaff_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtf_display_myKadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtf_displayAge, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jtf_displayContactNum, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                        .addComponent(jbt_updateExaminer, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jbt_removeExaminer, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(383, Short.MAX_VALUE))))
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayStaffrPanel_text_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayStaffPanel_text_Contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        createExaminerPanel_rightPanelLayout.setVerticalGroup(
            createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(displayStaffrPanel_text_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jtf_displayName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addComponent(displayStaffPanel_text_examiner_myKadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtf_display_myKadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(displayStaffPanel_text_Student_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtf_displayStaff_ID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayStaffrPanel_text_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_displayAge, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayStaffPanel_text_Contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_displayContactNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addComponent(jbt_removeExaminer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(jbt_updateExaminer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addComponent(displayStaffPanel_text_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(212, 212, 212))))
        );

        displayStaffPanel_text_Address.getAccessibleContext().setAccessibleName("Intake year: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createExaminerPanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createExaminerPanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_removeExaminerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_removeExaminerActionPerformed
        // TODO add your handling code here:
        int isConfirmed = 0;
        isConfirmed = JOptionPane.showConfirmDialog(jtf_displayAge, "Are you sure you want to remove this record?", "REMOVE RECORD CONFIRMAITON", HEIGHT);
        if(isConfirmed==0){
            maintainExamSys.removeRecord(staff.getStaffID(), "STAFF");
            searchStaff sstaff = new searchStaff();
            sstaff.closeFrame(frame);
        }
        else{
            JOptionPane.showMessageDialog(null, "Remove record fail!", "REMOVE RECORD FAIL", HEIGHT);
        }
    }//GEN-LAST:event_jbt_removeExaminerActionPerformed

    private void jbt_updateExaminerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_updateExaminerActionPerformed
        // TODO add your handling code here:
        JFrame frm = new JFrame();
        frm.add(new updateStaff(staff));
        frm.setTitle("STAFF RECORD");
        frm.setSize(1366, 730);
        frm.setLocationRelativeTo(null);
        frm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frm.setVisible(true);
        frm.setResizable(false);
        
    }//GEN-LAST:event_jbt_updateExaminerActionPerformed

    
    private void jtf_displayStaff_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_displayStaff_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_displayStaff_IDActionPerformed

    private void jtf_displayNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_displayNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_displayNameActionPerformed

    private void jtf_displayAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_displayAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_displayAgeActionPerformed

    private void jtf_display_myKadNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_display_myKadNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_display_myKadNumberActionPerformed

    private void jtf_displayContactNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_displayContactNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_displayContactNumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel createExaminerPanel_rightPanel;
    private java.awt.Label displayStaffPanel_text_Address;
    private java.awt.Label displayStaffPanel_text_Contact_number;
    private java.awt.Label displayStaffPanel_text_Student_ID;
    private java.awt.Label displayStaffPanel_text_examiner_myKadNumber;
    private java.awt.Label displayStaffrPanel_text_Age;
    private java.awt.Label displayStaffrPanel_text_Name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_removeExaminer;
    private javax.swing.JButton jbt_updateExaminer;
    private javax.swing.JTextArea jta_displayAddress;
    private javax.swing.JTextField jtf_displayAge;
    private javax.swing.JTextField jtf_displayContactNum;
    private javax.swing.JTextField jtf_displayName;
    private javax.swing.JTextField jtf_displayStaff_ID;
    private javax.swing.JTextField jtf_display_myKadNumber;
    // End of variables declaration//GEN-END:variables
}
