package ui;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import control.MaintainExaminationSystem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tommy
 */
import domain.examiner;
import domain.payment;
public class displayExaminer extends javax.swing.JPanel {
    private JFrame frame;

    /**
     * Creates new form createExaminer
     */
    private MaintainExaminationSystem maintainExamSys = new MaintainExaminationSystem();
    private int currentYear = 0;
    public displayExaminer(String userPosition, examiner examiner, JFrame frame) {
        initComponents();
        this.frame = frame;
        jbt_topUpBalance.setVisible(false);
        jbt_renewID.setVisible(false);
        this.examiner = examiner;
        jtf_displayName.setText(examiner.getexaminerName());
        jtf_display_myKadNumber.setText(examiner.getexaminerIC());
        jtf_displayStudent_ID.setText(examiner.getexaminerID());
        jtf_displayAge.setText(String.valueOf(examiner.getexaminerAge()));
        jtf_display_intakeYear.setText(String.valueOf(examiner.getexaminerIntakeYear()));
        jtf_display_contactNumber.setText(examiner.getexaminerContactNumber());
        jtf_displayCourse.setText(examiner.getexaminerCourse());
        currentYear = new java.util.Date().getYear()+1900;
         if(userPosition.equalsIgnoreCase("STAFF")==true){
             if((currentYear-examiner.getexaminerIntakeYear())>=2)
                 jbt_renewID.setVisible(true);
            
             jbt_topUpBalance.setVisible(true);
        }
            
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        createExaminerPanel_rightPanel = new javax.swing.JPanel();
        displayExaminerPanel_text_Name = new java.awt.Label();
        displayExaminerPanel_text_Intake_year = new java.awt.Label();
        displayExaminerPanel_text_Programme = new java.awt.Label();
        jbt_removeExaminer = new javax.swing.JButton();
        jbt_updateExaminer = new javax.swing.JButton();
        displayExaminerPanel_text_Age = new java.awt.Label();
        displayExaminerPanel_text_Student_ID = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf_displayStudent_ID = new javax.swing.JTextField();
        jtf_displayName = new javax.swing.JTextField();
        jtf_displayCourse = new javax.swing.JTextField();
        jtf_displayAge = new javax.swing.JTextField();
        displayExaminerPanel_text_examiner_myKadNumber = new java.awt.Label();
        jtf_display_myKadNumber = new javax.swing.JTextField();
        jtf_display_intakeYear = new javax.swing.JTextField();
        displayExaminerPanel_text_examiner_contact_number = new java.awt.Label();
        jtf_display_contactNumber = new javax.swing.JTextField();
        jbt_renewID = new javax.swing.JButton();
        jbt_topUpBalance = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        createExaminerPanel_rightPanel.setBackground(new java.awt.Color(204, 255, 204));
        createExaminerPanel_rightPanel.setToolTipText("");

        displayExaminerPanel_text_Name.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayExaminerPanel_text_Name.setText("Name");

        displayExaminerPanel_text_Intake_year.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayExaminerPanel_text_Intake_year.setText("Intake year");

        displayExaminerPanel_text_Programme.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayExaminerPanel_text_Programme.setText("Course");

        jbt_removeExaminer.setBackground(new java.awt.Color(255, 204, 153));
        jbt_removeExaminer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_removeExaminer.setText("Remove");
        jbt_removeExaminer.setToolTipText("Click to remove record");
        jbt_removeExaminer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_removeExaminer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_removeExaminerActionPerformed(evt);
            }
        });

        jbt_updateExaminer.setBackground(new java.awt.Color(255, 204, 153));
        jbt_updateExaminer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_updateExaminer.setText("Update");
        jbt_updateExaminer.setToolTipText("Click to update record");
        jbt_updateExaminer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_updateExaminer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_updateExaminerActionPerformed(evt);
            }
        });

        displayExaminerPanel_text_Age.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayExaminerPanel_text_Age.setText("Age");

        displayExaminerPanel_text_Student_ID.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayExaminerPanel_text_Student_ID.setText("Student ID");

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setToolTipText("Bonjour");

        jLabel2.setToolTipText("Bonjour");

        jtf_displayStudent_ID.setEditable(false);
        jtf_displayStudent_ID.setBackground(new java.awt.Color(204, 204, 255));
        jtf_displayStudent_ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_displayStudent_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_displayStudent_IDActionPerformed(evt);
            }
        });

        jtf_displayName.setEditable(false);
        jtf_displayName.setBackground(new java.awt.Color(204, 204, 255));
        jtf_displayName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_displayName.setToolTipText("");
        jtf_displayName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_displayNameActionPerformed(evt);
            }
        });

        jtf_displayCourse.setEditable(false);
        jtf_displayCourse.setBackground(new java.awt.Color(204, 204, 255));
        jtf_displayCourse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_displayCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_displayCourseActionPerformed(evt);
            }
        });

        jtf_displayAge.setEditable(false);
        jtf_displayAge.setBackground(new java.awt.Color(204, 204, 255));
        jtf_displayAge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_displayAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_displayAgeActionPerformed(evt);
            }
        });

        displayExaminerPanel_text_examiner_myKadNumber.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayExaminerPanel_text_examiner_myKadNumber.setText("myKad number");

        jtf_display_myKadNumber.setEditable(false);
        jtf_display_myKadNumber.setBackground(new java.awt.Color(204, 204, 255));
        jtf_display_myKadNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_display_myKadNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_display_myKadNumberActionPerformed(evt);
            }
        });

        jtf_display_intakeYear.setEditable(false);
        jtf_display_intakeYear.setBackground(new java.awt.Color(204, 204, 255));
        jtf_display_intakeYear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_display_intakeYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_display_intakeYearActionPerformed(evt);
            }
        });

        displayExaminerPanel_text_examiner_contact_number.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayExaminerPanel_text_examiner_contact_number.setText("Contact number");

        jtf_display_contactNumber.setEditable(false);
        jtf_display_contactNumber.setBackground(new java.awt.Color(204, 204, 255));
        jtf_display_contactNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_display_contactNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_display_contactNumberActionPerformed(evt);
            }
        });

        jbt_renewID.setBackground(new java.awt.Color(255, 204, 153));
        jbt_renewID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_renewID.setText("Renew ID");
        jbt_renewID.setToolTipText("Click to renew this examiner's student ID");
        jbt_renewID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_renewID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_renewIDActionPerformed(evt);
            }
        });

        jbt_topUpBalance.setBackground(new java.awt.Color(255, 204, 153));
        jbt_topUpBalance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_topUpBalance.setText("Top up");
        jbt_topUpBalance.setToolTipText("Click to top up balance for this examiner");
        jbt_topUpBalance.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_topUpBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_topUpBalanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createExaminerPanel_rightPanelLayout = new javax.swing.GroupLayout(createExaminerPanel_rightPanel);
        createExaminerPanel_rightPanel.setLayout(createExaminerPanel_rightPanelLayout);
        createExaminerPanel_rightPanelLayout.setHorizontalGroup(
            createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayExaminerPanel_text_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayExaminerPanel_text_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayExaminerPanel_text_examiner_myKadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayExaminerPanel_text_Student_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayExaminerPanel_text_Intake_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayExaminerPanel_text_examiner_contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayExaminerPanel_text_Programme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_displayName, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtf_displayStudent_ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                        .addComponent(jtf_display_myKadNumber, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbt_updateExaminer, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtf_display_intakeYear, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtf_displayAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                                    .addComponent(jtf_display_contactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_displayCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbt_renewID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbt_topUpBalance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbt_removeExaminer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(217, 217, 217)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(229, Short.MAX_VALUE))
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGap(487, 487, 487)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        createExaminerPanel_rightPanelLayout.setVerticalGroup(
            createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(displayExaminerPanel_text_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_displayName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(displayExaminerPanel_text_examiner_myKadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_display_myKadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(displayExaminerPanel_text_Student_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_displayStudent_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayExaminerPanel_text_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_displayAge, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jtf_display_intakeYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                        .addComponent(displayExaminerPanel_text_Intake_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(displayExaminerPanel_text_examiner_contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtf_display_contactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(displayExaminerPanel_text_Programme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addComponent(jtf_displayCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jbt_topUpBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(29, 29, 29)
                                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbt_renewID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(223, 290, Short.MAX_VALUE))))
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jbt_updateExaminer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_removeExaminer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createExaminerPanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createExaminerPanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_removeExaminerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_removeExaminerActionPerformed
        // TODO add your handling code here:
        int isConfirmed = 0;
        isConfirmed = JOptionPane.showConfirmDialog(jtf_displayAge, "Are you sure you want to remove this record?", "REMOVE RECORD CONFIRMAITON", HEIGHT);
        if(isConfirmed==0){
            maintainExamSys.removeRecord(examiner.getexaminerID(), "EXAMINER");
            searchExaminer examiner = new searchExaminer("");
            examiner.closeFrame(frame);
        }
        else{
            JOptionPane.showMessageDialog(null, "Remove record fail!", "REMOVE RECORD FAIL", HEIGHT);
        }
    }//GEN-LAST:event_jbt_removeExaminerActionPerformed

    
    private void jbt_updateExaminerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_updateExaminerActionPerformed
        // TODO add your handling code here:
        JFrame frm = new JFrame();
        frm.add(new updateExaminer(examiner));
        frm.setTitle("STUDENT RECORD");
        frm.setSize(1366, 730);
        frm.setLocationRelativeTo(null);
        frm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frm.setVisible(true);
        
    }//GEN-LAST:event_jbt_updateExaminerActionPerformed

    
    private void jtf_displayStudent_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_displayStudent_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_displayStudent_IDActionPerformed

    private void jtf_displayNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_displayNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_displayNameActionPerformed

    private void jtf_displayCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_displayCourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_displayCourseActionPerformed

    private void jtf_displayAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_displayAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_displayAgeActionPerformed

    private void jtf_display_myKadNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_display_myKadNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_display_myKadNumberActionPerformed

    private void jtf_display_intakeYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_display_intakeYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_display_intakeYearActionPerformed

    private void jtf_display_contactNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_display_contactNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_display_contactNumberActionPerformed

    private void jbt_renewIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_renewIDActionPerformed
        // TODO add your handling code here:
        int isConfirmed = 0;
            isConfirmed = JOptionPane.showConfirmDialog(null, "Are you sure you want to renew this student ID?","RENEW STUDENT ID CONFIRMATION", HEIGHT);
            if(isConfirmed==0){ 
            payment payment = new payment();
            payment.setExaminerID(examiner.getexaminerID());
            payment.setExaminerName(examiner.getexaminerName());
            payment.setPaymentCost(50.00);
            payment.setPaymentDescription("Renew student ID");
            String paymentCode = "";
            int paymentListCount = 0;
            if(maintainExamSys.getPaymentList().isEmpty()==true)
                paymentListCount = 1;
            else
                paymentListCount = maintainExamSys.getPaymentList().size()+1;
            
            if(paymentListCount+1<10){
                paymentCode = "P00"+paymentListCount;
            }
            else if(paymentListCount+1<100){
                paymentCode = "P0"+paymentListCount;
            }
            else if(paymentListCount+1<1000){
                paymentCode = "P"+paymentListCount;
            }
            payment.setPaymentID(paymentCode);
            payment.setPaymentName("RENEW STUDENT ID");
            maintainExamSys.createPayment(payment);
            examiner.setexaminerIntakeYear(currentYear);
            maintainExamSys.updateExaminer(examiner);
            jbt_renewID.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(jtf_displayStudent_ID, "Renew Student ID fail!", "RENEW STUDENT ID FAIL", HEIGHT);
            }
        
    }//GEN-LAST:event_jbt_renewIDActionPerformed

    private void jbt_topUpBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_topUpBalanceActionPerformed
        // TODO add your handling code here:
        double topupBalance = 0.0;
        try{
            topupBalance = Double.parseDouble(JOptionPane.showInputDialog(jtf_display_contactNumber, "Please key in the total value", "TOP UP VALUE", JOptionPane.INFORMATION_MESSAGE));
            if(topupBalance>=10&&topupBalance<=500){
                int isConfirmed = 0;
            isConfirmed = JOptionPane.showConfirmDialog(jtf_displayStudent_ID, "Are you sure you want to top up this ID with total RM "+topupBalance,"TOP UP CONFIRMATION", HEIGHT);
            if(isConfirmed==0){
                maintainExamSys.topupBalance(examiner.getexaminerID(), examiner.getexaminerBalance()+topupBalance);
            JOptionPane.showMessageDialog(jtf_displayStudent_ID, "Top up success!", "TOP UP  SUCCESS", HEIGHT);
            }
            else{
                JOptionPane.showMessageDialog(jtf_displayStudent_ID, "Top up fail!", "TOP UP  FAIL", HEIGHT);
            }
        }
        else
            JOptionPane.showMessageDialog(jtf_displayStudent_ID, "The amount less than RM 10 and more than RM 500 is not acceptable", "TOP UP  FAIL", JOptionPane.ERROR_MESSAGE);
        }
        catch(NumberFormatException ex ){
            JOptionPane.showMessageDialog(jtf_displayStudent_ID,"Input must be number!","TOP UP FAIL", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbt_topUpBalanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel createExaminerPanel_rightPanel;
    private java.awt.Label displayExaminerPanel_text_Age;
    private java.awt.Label displayExaminerPanel_text_Intake_year;
    private java.awt.Label displayExaminerPanel_text_Name;
    private java.awt.Label displayExaminerPanel_text_Programme;
    private java.awt.Label displayExaminerPanel_text_Student_ID;
    private java.awt.Label displayExaminerPanel_text_examiner_contact_number;
    private java.awt.Label displayExaminerPanel_text_examiner_myKadNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbt_removeExaminer;
    private javax.swing.JButton jbt_renewID;
    private javax.swing.JButton jbt_topUpBalance;
    private javax.swing.JButton jbt_updateExaminer;
    private javax.swing.JTextField jtf_displayAge;
    private javax.swing.JTextField jtf_displayCourse;
    private javax.swing.JTextField jtf_displayName;
    private javax.swing.JTextField jtf_displayStudent_ID;
    private javax.swing.JTextField jtf_display_contactNumber;
    private javax.swing.JTextField jtf_display_intakeYear;
    private javax.swing.JTextField jtf_display_myKadNumber;
    // End of variables declaration//GEN-END:variables
    private examiner examiner;


}

