package ui;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import domain.staff;
import control.MaintainExaminationSystem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tommy
 */
public class displayStaffOwnDetail extends javax.swing.JPanel {

    /**
     * Creates new form createExaminer
     */
    private staff currentStaff = new staff();
    private MaintainExaminationSystem maintainExamSys = new MaintainExaminationSystem();
    
    public displayStaffOwnDetail(staff staff) {
        initComponents();
        currentStaff = staff;
        updateField(staff.getStaffID());
    }
    
    public void updateField(String staffID){
        currentStaff = maintainExamSys.getSelectedStaff(staffID);
        jtf_displayName.setText(currentStaff.getSatffName());
        jtf_display_myKadNumber.setText(currentStaff.getStaffIC());
        jtf_displayStaff_ID.setText(currentStaff.getStaffID());
        jtf_displayAge.setText(String.valueOf(currentStaff.getStaffAge()));
        jtf_displayContactNum.setText(currentStaff.getStaffContactNumber());
        jta_displayAddress.setText(currentStaff.getStaffAddress());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        createExaminerPanel_rightPanel = new javax.swing.JPanel();
        displayStaffPanel_text_Name = new java.awt.Label();
        displayStaffPanel_text_Address = new java.awt.Label();
        jbt_updateStaff = new javax.swing.JButton();
        displayStaffrPanel_text_Age = new java.awt.Label();
        displayStaffPanel_text_Student_ID = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf_displayStaff_ID = new javax.swing.JTextField();
        jtf_displayName = new javax.swing.JTextField();
        jtf_displayAge = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_displayAddress = new javax.swing.JTextArea();
        displayStaffPanel_text_examiner_myKadNumber = new java.awt.Label();
        jtf_display_myKadNumber = new javax.swing.JTextField();
        displayStaffPanel_text_Contact_number = new java.awt.Label();
        jtf_displayContactNum = new javax.swing.JTextField();
        jbt_refresh = new javax.swing.JButton();
        jbt_changePassword = new javax.swing.JButton();
        updateStaffPanel_leftPanel1 = new javax.swing.JPanel();
        updateStaffPanel_text_Record = new java.awt.Label();
        updateStaffPanel_text_Staff = new java.awt.Label();

        setBackground(new java.awt.Color(0, 0, 0));

        createExaminerPanel_rightPanel.setBackground(new java.awt.Color(204, 255, 204));
        createExaminerPanel_rightPanel.setToolTipText("");

        displayStaffPanel_text_Name.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayStaffPanel_text_Name.setText("Name");

        displayStaffPanel_text_Address.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayStaffPanel_text_Address.setText("Address");

        jbt_updateStaff.setBackground(new java.awt.Color(255, 204, 153));
        jbt_updateStaff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_updateStaff.setText("Update");
        jbt_updateStaff.setToolTipText("Click to update record");
        jbt_updateStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_updateStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_updateStaffActionPerformed(evt);
            }
        });

        displayStaffrPanel_text_Age.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayStaffrPanel_text_Age.setText("Age");

        displayStaffPanel_text_Student_ID.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayStaffPanel_text_Student_ID.setText("Staff ID");

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setToolTipText("Bonjour");

        jLabel2.setToolTipText("Bonjour");

        jtf_displayStaff_ID.setEditable(false);
        jtf_displayStaff_ID.setBackground(new java.awt.Color(204, 204, 255));
        jtf_displayStaff_ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_displayStaff_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_displayStaff_IDActionPerformed(evt);
            }
        });

        jtf_displayName.setEditable(false);
        jtf_displayName.setBackground(new java.awt.Color(204, 204, 255));
        jtf_displayName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_displayName.setToolTipText("");
        jtf_displayName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_displayNameActionPerformed(evt);
            }
        });

        jtf_displayAge.setEditable(false);
        jtf_displayAge.setBackground(new java.awt.Color(204, 204, 255));
        jtf_displayAge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_displayAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_displayAgeActionPerformed(evt);
            }
        });

        jta_displayAddress.setEditable(false);
        jta_displayAddress.setBackground(new java.awt.Color(204, 204, 255));
        jta_displayAddress.setColumns(20);
        jta_displayAddress.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jta_displayAddress.setRows(5);
        jScrollPane1.setViewportView(jta_displayAddress);

        displayStaffPanel_text_examiner_myKadNumber.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayStaffPanel_text_examiner_myKadNumber.setText("myKad number");

        jtf_display_myKadNumber.setEditable(false);
        jtf_display_myKadNumber.setBackground(new java.awt.Color(204, 204, 255));
        jtf_display_myKadNumber.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_display_myKadNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_display_myKadNumberActionPerformed(evt);
            }
        });

        displayStaffPanel_text_Contact_number.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        displayStaffPanel_text_Contact_number.setText("Contact number");

        jtf_displayContactNum.setEditable(false);
        jtf_displayContactNum.setBackground(new java.awt.Color(204, 204, 255));
        jtf_displayContactNum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_displayContactNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_displayContactNumActionPerformed(evt);
            }
        });

        jbt_refresh.setBackground(new java.awt.Color(255, 204, 153));
        jbt_refresh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_refresh.setText("Refresh");
        jbt_refresh.setToolTipText("Click to update record");
        jbt_refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_refreshActionPerformed(evt);
            }
        });

        jbt_changePassword.setBackground(new java.awt.Color(255, 204, 153));
        jbt_changePassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_changePassword.setText("Change password");
        jbt_changePassword.setToolTipText("Click to update record");
        jbt_changePassword.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_changePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createExaminerPanel_rightPanelLayout = new javax.swing.GroupLayout(createExaminerPanel_rightPanel);
        createExaminerPanel_rightPanel.setLayout(createExaminerPanel_rightPanelLayout);
        createExaminerPanel_rightPanelLayout.setHorizontalGroup(
            createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayStaffPanel_text_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayStaffrPanel_text_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayStaffPanel_text_examiner_myKadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayStaffPanel_text_Student_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1))
                    .addComponent(displayStaffPanel_text_Contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayStaffPanel_text_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addComponent(jtf_displayName, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtf_displayStaff_ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addComponent(jtf_display_myKadNumber, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_displayAge, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_displayContactNum, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                        .addComponent(jbt_updateStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jbt_refresh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbt_changePassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        createExaminerPanel_rightPanelLayout.setVerticalGroup(
            createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addComponent(jbt_changePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_updateStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(displayStaffPanel_text_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_displayName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(displayStaffPanel_text_examiner_myKadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_display_myKadNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(displayStaffPanel_text_Student_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_displayStaff_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(displayStaffrPanel_text_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_displayAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_displayContactNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayStaffPanel_text_Contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addComponent(displayStaffPanel_text_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        displayStaffPanel_text_Address.getAccessibleContext().setAccessibleName("Intake year: ");

        updateStaffPanel_leftPanel1.setBackground(new java.awt.Color(204, 204, 255));
        updateStaffPanel_leftPanel1.setToolTipText("");

        updateStaffPanel_text_Record.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        updateStaffPanel_text_Record.setText("Record");

        updateStaffPanel_text_Staff.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        updateStaffPanel_text_Staff.setText("My");

        javax.swing.GroupLayout updateStaffPanel_leftPanel1Layout = new javax.swing.GroupLayout(updateStaffPanel_leftPanel1);
        updateStaffPanel_leftPanel1.setLayout(updateStaffPanel_leftPanel1Layout);
        updateStaffPanel_leftPanel1Layout.setHorizontalGroup(
            updateStaffPanel_leftPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateStaffPanel_leftPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(updateStaffPanel_leftPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateStaffPanel_text_Staff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateStaffPanel_text_Record, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        updateStaffPanel_leftPanel1Layout.setVerticalGroup(
            updateStaffPanel_leftPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateStaffPanel_leftPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateStaffPanel_text_Staff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateStaffPanel_text_Record, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(updateStaffPanel_leftPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createExaminerPanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateStaffPanel_leftPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(createExaminerPanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_updateStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_updateStaffActionPerformed
        // TODO add your handling code here:
        JFrame frm = new JFrame();
        frm.add(new updateStaff(currentStaff));
        frm.setTitle("STAFF RECORD");
        frm.setSize(1366, 730);
        frm.setLocationRelativeTo(null);
        frm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frm.setVisible(true);
        frm.setResizable(false);
        
    }//GEN-LAST:event_jbt_updateStaffActionPerformed

    
    private void jtf_displayStaff_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_displayStaff_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_displayStaff_IDActionPerformed

    private void jtf_displayNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_displayNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_displayNameActionPerformed

    private void jtf_displayAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_displayAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_displayAgeActionPerformed

    private void jtf_display_myKadNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_display_myKadNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_display_myKadNumberActionPerformed

    private void jtf_displayContactNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_displayContactNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_displayContactNumActionPerformed

    private void jbt_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_refreshActionPerformed
        // TODO add your handling code here:
        updateField(currentStaff.getStaffID());
    }//GEN-LAST:event_jbt_refreshActionPerformed

    private void jbt_changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_changePasswordActionPerformed
        // TODO add your handling code here:
        if((JOptionPane.showConfirmDialog(null, "Are you sure you want to change your password?","PASSWORD CHANGE CONFIRMATION",JOptionPane.INFORMATION_MESSAGE)==0)){
            String oldPassword = "", newPassword = "";
            oldPassword = JOptionPane.showInputDialog(null,"Please enter your previous password:","USER VERTIFICATION",JOptionPane.INFORMATION_MESSAGE);
            if(oldPassword.isEmpty()==false){
                if(oldPassword.equalsIgnoreCase(currentStaff.getStaffPassword())){
                newPassword = JOptionPane.showInputDialog(null, "Please enter the new password here, the new password should not be same as the previous password.", "PASSWORD CHANGE PROCESS", JOptionPane.INFORMATION_MESSAGE);
                if(newPassword.equalsIgnoreCase(currentStaff.getStaffPassword())){
                    JOptionPane.showMessageDialog(null, "The password is same as the previous password!! Operation interrupted!!", "PASSWORD CHANGE FAIL", JOptionPane.ERROR_MESSAGE);
                }
                else{
                    currentStaff.setStaffPassword(newPassword);
                    maintainExamSys.updateStaff(currentStaff);
                }
                    
                
            }
                else
                    JOptionPane.showMessageDialog(null,"Password wrong, please make sure you have entered the correct password ","PASSWORD CHANGE INTERRUPTED", JOptionPane.ERROR_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(null,"Password field is empty, please type in your old password before we get into the next step", "PASSWORD CHANGE INTERRUPTED", JOptionPane.ERROR_MESSAGE);
    }
        else
            JOptionPane.showMessageDialog(null,"Password change canceled by user", "PASSWORD CHANGE CANCELED", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jbt_changePasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel createExaminerPanel_rightPanel;
    private java.awt.Label displayStaffPanel_text_Address;
    private java.awt.Label displayStaffPanel_text_Contact_number;
    private java.awt.Label displayStaffPanel_text_Name;
    private java.awt.Label displayStaffPanel_text_Student_ID;
    private java.awt.Label displayStaffPanel_text_examiner_myKadNumber;
    private java.awt.Label displayStaffrPanel_text_Age;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_changePassword;
    private javax.swing.JButton jbt_refresh;
    private javax.swing.JButton jbt_updateStaff;
    private javax.swing.JTextArea jta_displayAddress;
    private javax.swing.JTextField jtf_displayAge;
    private javax.swing.JTextField jtf_displayContactNum;
    private javax.swing.JTextField jtf_displayName;
    private javax.swing.JTextField jtf_displayStaff_ID;
    private javax.swing.JTextField jtf_display_myKadNumber;
    private javax.swing.JPanel updateStaffPanel_leftPanel1;
    private java.awt.Label updateStaffPanel_text_Record;
    private java.awt.Label updateStaffPanel_text_Staff;
    // End of variables declaration//GEN-END:variables
}
