package ui;


import control.MaintainExaminationSystem;
import da.ExaminerTableModel;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.*;
import static ui.searchExaminer.DATABASE_URL;
import domain.staff;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tommy
 */
import da.ExaminerTableModel;
import domain.examiner;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
public class searchStaff extends javax.swing.JPanel {

    /**
     * Creates new form createExaminer
     */
    private staff staff;
    private examiner examiner;
    private MaintainExaminationSystem maintainExamSys = new MaintainExaminationSystem();
    static final String DATABASE_URL = "jdbc:derby://localhost:1527/f:/examinationSystemDB;create=true";
    static final String USERNAME = "taruc";
    static final String PASSWORD = "taruc";
    static final String DEFAULT_QUERY = "SELECT \"staffID\", \"staffName\", \"staffContactNumber\" FROM STAFF";
    
    private ExaminerTableModel tableModel;
    private JTable resultTable;
    private TableRowSorter<TableModel> sorter;
    private JTextField filterText = new JTextField();
    private String userOptions = "staffID";
    
    public searchStaff() {
        initComponents();
        this.buttonGroup1.add(jrb_byName);
        this.buttonGroup1.add(jrb_byAge);
        searchExaminerPanel_advancePanel.setVisible(false);
        drawTable();
        
    }
    
    public void drawTable(){
        try {
            tableModel = new ExaminerTableModel(DATABASE_URL, USERNAME, PASSWORD, DEFAULT_QUERY);
            displayTable.setModel(tableModel);
            sorter = new TableRowSorter<TableModel>(tableModel);
            displayTable.setRowSorter(sorter);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            tableModel.disconnectFromDatabase();
            System.exit(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        searchExaminerPanel_leftPanel = new javax.swing.JPanel();
        searchStaffPanel_text_Search = new java.awt.Label();
        searchStaffPanel_text_Record = new java.awt.Label();
        searchStaffPanel_text_Examiner = new java.awt.Label();
        searchExaminerPanel_rightPanel = new javax.swing.JPanel();
        jbt_Enter = new javax.swing.JButton();
        jtf_searchItems = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbt_searchRecord = new javax.swing.JButton();
        jbt_show_advance_options = new javax.swing.JButton();
        searchExaminerPanel_advancePanel = new javax.swing.JPanel();
        searchStaffPanel_text_Search_by = new javax.swing.JLabel();
        jrb_byName = new javax.swing.JRadioButton();
        jrb_byAge = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();
        jbt_refresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        searchExaminerPanel_leftPanel.setBackground(new java.awt.Color(204, 204, 255));
        searchExaminerPanel_leftPanel.setToolTipText("");

        searchStaffPanel_text_Search.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        searchStaffPanel_text_Search.setText("Search");

        searchStaffPanel_text_Record.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        searchStaffPanel_text_Record.setText("Record");

        searchStaffPanel_text_Examiner.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        searchStaffPanel_text_Examiner.setText("Staff");

        javax.swing.GroupLayout searchExaminerPanel_leftPanelLayout = new javax.swing.GroupLayout(searchExaminerPanel_leftPanel);
        searchExaminerPanel_leftPanel.setLayout(searchExaminerPanel_leftPanelLayout);
        searchExaminerPanel_leftPanelLayout.setHorizontalGroup(
            searchExaminerPanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchExaminerPanel_leftPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(searchExaminerPanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchStaffPanel_text_Search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchStaffPanel_text_Examiner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchStaffPanel_text_Record, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        searchExaminerPanel_leftPanelLayout.setVerticalGroup(
            searchExaminerPanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchExaminerPanel_leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchStaffPanel_text_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchStaffPanel_text_Examiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchStaffPanel_text_Record, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchExaminerPanel_rightPanel.setBackground(new java.awt.Color(204, 255, 204));
        searchExaminerPanel_rightPanel.setToolTipText("");

        jbt_Enter.setBackground(new java.awt.Color(255, 204, 153));
        jbt_Enter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_Enter.setText("Enter");
        jbt_Enter.setToolTipText("Click to enter record");
        jbt_Enter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_EnterActionPerformed(evt);
            }
        });

        jtf_searchItems.setBackground(new java.awt.Color(204, 204, 255));
        jtf_searchItems.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_searchItems.setToolTipText("What are you looking for?");

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setToolTipText("Bonjour");

        jLabel2.setToolTipText("Ni hao");

        jbt_searchRecord.setBackground(new java.awt.Color(255, 204, 153));
        jbt_searchRecord.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_searchRecord.setText("Search ID");
        jbt_searchRecord.setToolTipText("Click to search the record");
        jbt_searchRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_searchRecordActionPerformed(evt);
            }
        });

        jbt_show_advance_options.setBackground(new java.awt.Color(255, 204, 153));
        jbt_show_advance_options.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_show_advance_options.setText("Show advance options");
        jbt_show_advance_options.setToolTipText("Looking for some things more detail?");
        jbt_show_advance_options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_show_advance_optionsActionPerformed(evt);
            }
        });

        searchExaminerPanel_advancePanel.setBackground(new java.awt.Color(204, 255, 204));

        searchStaffPanel_text_Search_by.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchStaffPanel_text_Search_by.setText("Search by:");

        jrb_byName.setBackground(new java.awt.Color(204, 255, 204));
        jrb_byName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrb_byName.setText("Name");
        jrb_byName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_byNameActionPerformed(evt);
            }
        });

        jrb_byAge.setBackground(new java.awt.Color(204, 255, 204));
        jrb_byAge.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrb_byAge.setText("Age");
        jrb_byAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_byAgeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchExaminerPanel_advancePanelLayout = new javax.swing.GroupLayout(searchExaminerPanel_advancePanel);
        searchExaminerPanel_advancePanel.setLayout(searchExaminerPanel_advancePanelLayout);
        searchExaminerPanel_advancePanelLayout.setHorizontalGroup(
            searchExaminerPanel_advancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchExaminerPanel_advancePanelLayout.createSequentialGroup()
                .addComponent(searchStaffPanel_text_Search_by)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb_byName)
                .addGap(18, 18, 18)
                .addComponent(jrb_byAge)
                .addContainerGap())
        );
        searchExaminerPanel_advancePanelLayout.setVerticalGroup(
            searchExaminerPanel_advancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchExaminerPanel_advancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(searchStaffPanel_text_Search_by)
                .addComponent(jrb_byName)
                .addComponent(jrb_byAge))
        );

        displayTable.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Staff ID", "Gender", "MyKad", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        displayTable.setToolTipText("Here is it");
        jScrollPane1.setViewportView(displayTable);

        jbt_refresh.setBackground(new java.awt.Color(255, 204, 153));
        jbt_refresh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_refresh.setText("Refresh");
        jbt_refresh.setToolTipText("Click to enter record");
        jbt_refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchExaminerPanel_rightPanelLayout = new javax.swing.GroupLayout(searchExaminerPanel_rightPanel);
        searchExaminerPanel_rightPanel.setLayout(searchExaminerPanel_rightPanelLayout);
        searchExaminerPanel_rightPanelLayout.setHorizontalGroup(
            searchExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchExaminerPanel_rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGap(942, 942, 942)
                        .addGroup(searchExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jLabel1)
                                .addGap(127, 127, 127))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(searchExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(searchExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchExaminerPanel_advancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(searchExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addComponent(jtf_searchItems, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbt_searchRecord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbt_show_advance_options)))
                        .addContainerGap(294, Short.MAX_VALUE))))
            .addGroup(searchExaminerPanel_rightPanelLayout.createSequentialGroup()
                .addGap(695, 695, 695)
                .addComponent(jbt_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbt_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(searchExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(searchExaminerPanel_rightPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(183, Short.MAX_VALUE)))
        );
        searchExaminerPanel_rightPanelLayout.setVerticalGroup(
            searchExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchExaminerPanel_rightPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(searchExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_searchRecord)
                    .addComponent(jtf_searchItems, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_show_advance_options))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchExaminerPanel_advancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(searchExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 411, Short.MAX_VALUE)
                        .addGroup(searchExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbt_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbt_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(searchExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchExaminerPanel_rightPanelLayout.createSequentialGroup()
                    .addContainerGap(119, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(119, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(searchExaminerPanel_leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchExaminerPanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchExaminerPanel_leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(searchExaminerPanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_EnterActionPerformed
        // TODO add your handling code here:
        
        
        
        staff selectedStaff = null;
        for(int i= 0;i<displayTable.getSelectedRows().length;i++){
            selectedStaff = maintainExamSys.getSelectedStaff(String.valueOf(displayTable.getValueAt(displayTable.getSelectedRows()[i], 0)));
            if(selectedStaff!=null){
                JFrame frm = new JFrame();
        frm.add(new displayStaff(selectedStaff, frm));
        frm.setTitle("STAFF RECORD");
        frm.setSize(900, 570);
        frm.setLocationRelativeTo(null);
        frm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frm.setVisible(true);
        frm.setResizable(false);
            }
            else
                JOptionPane.showMessageDialog(null, "Record not found in database.","RECORD NOT FOUND", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbt_EnterActionPerformed

    public void closeFrame(JFrame frame){
        frame.dispose();
    }
    private void jbt_show_advance_optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_show_advance_optionsActionPerformed
        // TODO add your handling code here:
        if(switch_advanceSearch == 1){
            searchExaminerPanel_advancePanel.setVisible(false);
            buttonGroup1.clearSelection();
            jbt_show_advance_options.setText("Show advance options");
            jbt_searchRecord.setText("Search ID");
            switch_advanceSearch = 0;
        }
        else{
            searchExaminerPanel_advancePanel.setVisible(true);
            jbt_show_advance_options.setText("Hide advance options");
            switch_advanceSearch = 1;
        }
    }//GEN-LAST:event_jbt_show_advance_optionsActionPerformed

    private void jrb_byNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_byNameActionPerformed
        // TODO add your handling code here:
        jbt_searchRecord.setText("Search Name");
        userOptions = "staffName";
    }//GEN-LAST:event_jrb_byNameActionPerformed

    private void jrb_byAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_byAgeActionPerformed
        // TODO add your handling code here:
        jbt_searchRecord.setText("Search Age");
        userOptions = "staffAge";
    }//GEN-LAST:event_jrb_byAgeActionPerformed

    private void jbt_searchRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_searchRecordActionPerformed
        // TODO add your handling code here:
        String a = "";
            try {
                if(jtf_searchItems.getText().isEmpty()==false){
                if(userOptions.equalsIgnoreCase("staffAge")==true){
                    a = "SELECT \"staffID\", \"staffName\", \"staffContactNumber\" FROM STAFF WHERE \""+userOptions+"\"="+Integer.parseInt(jtf_searchItems.getText());
                }
                    
                else
                    a = "SELECT \"staffID\", \"staffName\", \"staffContactNumber\" FROM STAFF WHERE \""+userOptions+"\"='"+jtf_searchItems.getText()+"'";
                tableModel.setQuery(a);
                }
                else
                    JOptionPane.showMessageDialog(null,"Try to type in some detail so we can search it for you","USER INPUT REQUIRED", JOptionPane.WARNING_MESSAGE);
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);

            }
    }//GEN-LAST:event_jbt_searchRecordActionPerformed

    private void jbt_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_refreshActionPerformed
        // TODO add your handling code here:
        try {
            String a = "SELECT \"staffID\", \"staffName\", \"staffContactNumber\" FROM STAFF";
            tableModel.setQuery(a);
            
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);

            }
    }//GEN-LAST:event_jbt_refreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable displayTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_Enter;
    private javax.swing.JButton jbt_refresh;
    private javax.swing.JButton jbt_searchRecord;
    private javax.swing.JButton jbt_show_advance_options;
    private javax.swing.JRadioButton jrb_byAge;
    private javax.swing.JRadioButton jrb_byName;
    private javax.swing.JTextField jtf_searchItems;
    private javax.swing.JPanel searchExaminerPanel_advancePanel;
    private javax.swing.JPanel searchExaminerPanel_leftPanel;
    private javax.swing.JPanel searchExaminerPanel_rightPanel;
    private java.awt.Label searchStaffPanel_text_Examiner;
    private java.awt.Label searchStaffPanel_text_Record;
    private java.awt.Label searchStaffPanel_text_Search;
    private javax.swing.JLabel searchStaffPanel_text_Search_by;
    // End of variables declaration//GEN-END:variables
    private int switch_advanceSearch = 0;
    private JScrollPane jpane = new JScrollPane(displayTable);
}
