package ui;


import static java.awt.event.WindowListener.*;
import javax.swing.JOptionPane;
import javax.swing.*;
import control.*;
import domain.*;
import da.ExaminerTableModel;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tommy
 */
public class searchSubject extends javax.swing.JPanel {

    /**
     * Creates new form createExaminer
     */
    private TableRowSorter<TableModel> sorter;
    
    public searchSubject() {
        initComponents();
        this.buttonGroup1.add(jrb_byName);
        this.buttonGroup1.add(jrb_byCourseID);
        this.buttonGroup1.add(jrb_byLecturer);
        searchSubjectPanel_advancePanel.setVisible(false);
        drawTable();
        
    }
    
    public void drawTable(){
        try {
            tableModel = new ExaminerTableModel(DATABASE_URL, USERNAME, PASSWORD, DEFAULT_QUERY);
            jTable1.setModel(tableModel);
            sorter = new TableRowSorter<TableModel>(tableModel);
            jTable1.setRowSorter(sorter);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            tableModel.disconnectFromDatabase();
            System.exit(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        searchSubjectPanel_leftPanel = new javax.swing.JPanel();
        searchSubjectPanel_text_Search = new java.awt.Label();
        searchSubjectPanel_text_Record = new java.awt.Label();
        searchSubjectPanel_text_Subject = new java.awt.Label();
        searchSubjectPanel_rightPanel = new javax.swing.JPanel();
        jbt_Enter = new javax.swing.JButton();
        jtf_searchItems = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jbt_searchRecord = new javax.swing.JButton();
        jbt_show_advance_options = new javax.swing.JButton();
        searchSubjectPanel_advancePanel = new javax.swing.JPanel();
        searchExaminerPanel_text_Search_by = new javax.swing.JLabel();
        jrb_byName = new javax.swing.JRadioButton();
        jrb_byCourseID = new javax.swing.JRadioButton();
        jrb_byLecturer = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbt_refresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        searchSubjectPanel_leftPanel.setBackground(new java.awt.Color(204, 204, 255));
        searchSubjectPanel_leftPanel.setToolTipText("");

        searchSubjectPanel_text_Search.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        searchSubjectPanel_text_Search.setText("Search");

        searchSubjectPanel_text_Record.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        searchSubjectPanel_text_Record.setText("Record");

        searchSubjectPanel_text_Subject.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        searchSubjectPanel_text_Subject.setText("Subject");

        javax.swing.GroupLayout searchSubjectPanel_leftPanelLayout = new javax.swing.GroupLayout(searchSubjectPanel_leftPanel);
        searchSubjectPanel_leftPanel.setLayout(searchSubjectPanel_leftPanelLayout);
        searchSubjectPanel_leftPanelLayout.setHorizontalGroup(
            searchSubjectPanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchSubjectPanel_leftPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(searchSubjectPanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchSubjectPanel_text_Search, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchSubjectPanel_text_Subject, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchSubjectPanel_text_Record, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        searchSubjectPanel_leftPanelLayout.setVerticalGroup(
            searchSubjectPanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchSubjectPanel_leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchSubjectPanel_text_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchSubjectPanel_text_Subject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchSubjectPanel_text_Record, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchSubjectPanel_rightPanel.setBackground(new java.awt.Color(204, 255, 204));
        searchSubjectPanel_rightPanel.setToolTipText("");

        jbt_Enter.setBackground(new java.awt.Color(255, 204, 153));
        jbt_Enter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_Enter.setText("Enter");
        jbt_Enter.setToolTipText("Click to enter record");
        jbt_Enter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_EnterActionPerformed(evt);
            }
        });

        jtf_searchItems.setBackground(new java.awt.Color(204, 204, 255));
        jtf_searchItems.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_searchItems.setToolTipText("What are you looking for?");

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setToolTipText("Bonjour");

        jLabel2.setToolTipText("Ni hao");

        jbt_searchRecord.setBackground(new java.awt.Color(255, 204, 153));
        jbt_searchRecord.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_searchRecord.setText("Search ID");
        jbt_searchRecord.setToolTipText("Click to search the record");
        jbt_searchRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_searchRecordActionPerformed(evt);
            }
        });

        jbt_show_advance_options.setBackground(new java.awt.Color(255, 204, 153));
        jbt_show_advance_options.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_show_advance_options.setText("Show advance options");
        jbt_show_advance_options.setToolTipText("Looking for some things more detail?");
        jbt_show_advance_options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_show_advance_optionsActionPerformed(evt);
            }
        });

        searchSubjectPanel_advancePanel.setBackground(new java.awt.Color(204, 255, 204));

        searchExaminerPanel_text_Search_by.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        searchExaminerPanel_text_Search_by.setText("Search by:");

        jrb_byName.setBackground(new java.awt.Color(204, 255, 204));
        jrb_byName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrb_byName.setText("Name");
        jrb_byName.setToolTipText("Search by name");
        jrb_byName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_byNameActionPerformed(evt);
            }
        });

        jrb_byCourseID.setBackground(new java.awt.Color(204, 255, 204));
        jrb_byCourseID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrb_byCourseID.setText("Course ID");
        jrb_byCourseID.setToolTipText("Search by course");
        jrb_byCourseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_byCourseIDActionPerformed(evt);
            }
        });

        jrb_byLecturer.setBackground(new java.awt.Color(204, 255, 204));
        jrb_byLecturer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrb_byLecturer.setText("Lecturer");
        jrb_byLecturer.setToolTipText("Search by age");
        jrb_byLecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_byLecturerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchSubjectPanel_advancePanelLayout = new javax.swing.GroupLayout(searchSubjectPanel_advancePanel);
        searchSubjectPanel_advancePanel.setLayout(searchSubjectPanel_advancePanelLayout);
        searchSubjectPanel_advancePanelLayout.setHorizontalGroup(
            searchSubjectPanel_advancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchSubjectPanel_advancePanelLayout.createSequentialGroup()
                .addComponent(searchExaminerPanel_text_Search_by)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrb_byName)
                .addGap(18, 18, 18)
                .addComponent(jrb_byCourseID)
                .addGap(18, 18, 18)
                .addComponent(jrb_byLecturer)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        searchSubjectPanel_advancePanelLayout.setVerticalGroup(
            searchSubjectPanel_advancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchSubjectPanel_advancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(searchExaminerPanel_text_Search_by)
                .addComponent(jrb_byName)
                .addComponent(jrb_byCourseID)
                .addComponent(jrb_byLecturer))
        );

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jTable1.setModel(jTable1.getModel());
        jTable1.setToolTipText("Here is it");
        jScrollPane1.setViewportView(jTable1);

        jbt_refresh.setBackground(new java.awt.Color(255, 204, 153));
        jbt_refresh.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_refresh.setText("Refresh");
        jbt_refresh.setToolTipText("Click to enter record");
        jbt_refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchSubjectPanel_rightPanelLayout = new javax.swing.GroupLayout(searchSubjectPanel_rightPanel);
        searchSubjectPanel_rightPanel.setLayout(searchSubjectPanel_rightPanelLayout);
        searchSubjectPanel_rightPanelLayout.setHorizontalGroup(
            searchSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchSubjectPanel_rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchSubjectPanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(searchSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchSubjectPanel_advancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(searchSubjectPanel_rightPanelLayout.createSequentialGroup()
                                .addComponent(jtf_searchItems, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbt_searchRecord)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbt_show_advance_options)))
                        .addContainerGap(267, Short.MAX_VALUE))
                    .addGroup(searchSubjectPanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(searchSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(searchSubjectPanel_rightPanelLayout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addGroup(searchSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(searchSubjectPanel_rightPanelLayout.createSequentialGroup()
                                        .addGap(114, 114, 114)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchSubjectPanel_rightPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jbt_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addComponent(jbt_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))))
            .addGroup(searchSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(searchSubjectPanel_rightPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(183, Short.MAX_VALUE)))
        );
        searchSubjectPanel_rightPanelLayout.setVerticalGroup(
            searchSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchSubjectPanel_rightPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(searchSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_searchRecord)
                    .addComponent(jtf_searchItems, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_show_advance_options))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchSubjectPanel_advancePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 358, Short.MAX_VALUE)
                .addGroup(searchSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbt_Enter, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(searchSubjectPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchSubjectPanel_rightPanelLayout.createSequentialGroup()
                    .addContainerGap(119, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(119, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(searchSubjectPanel_leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchSubjectPanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchSubjectPanel_leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(searchSubjectPanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_EnterActionPerformed
        // TODO add your handling code here:
        subject selectedSubject = null;
        for(int i= 0;i<jTable1.getSelectedRows().length;i++){
            selectedSubject = maintainExamSys.getSelectedSubject(String.valueOf(jTable1.getValueAt(jTable1.getSelectedRows()[i], 0)));
            if(selectedSubject!=null){
                System.out.println("Subject ID: "+selectedSubject.getSubjectID());
                JFrame frm = new JFrame();
        frm.add(new displaySubject(selectedSubject, frm));
        frm.setTitle("SUBJECT RECORD");
        frm.setSize(900, 600);
        frm.setLocationRelativeTo(null);
        frm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frm.setVisible(true);
        frm.setResizable(false);
            }
            else
                JOptionPane.showMessageDialog(null, "Record not found in database.","RECORD NOT FOUND", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbt_EnterActionPerformed

    public void closeFrame(JFrame frame){
        frame.dispose();
    }
    private void jbt_show_advance_optionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_show_advance_optionsActionPerformed
        // TODO add your handling code here:
        if(switch_advanceSearch == 1){
            searchSubjectPanel_advancePanel.setVisible(false);
            buttonGroup1.clearSelection();
            jbt_show_advance_options.setText("Show advance options");
            jbt_searchRecord.setText("Search ID");
            switch_advanceSearch = 0;
        }
        else{
            searchSubjectPanel_advancePanel.setVisible(true);
            jbt_show_advance_options.setText("Hide advance options");
            switch_advanceSearch = 1;
        }
        userOptions = "subjectID";
    }//GEN-LAST:event_jbt_show_advance_optionsActionPerformed

    private void jrb_byCourseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_byCourseIDActionPerformed
        // TODO add your handling code here:
        jbt_searchRecord.setText("Search Course ID");
        userOptions = "courseID";
    }//GEN-LAST:event_jrb_byCourseIDActionPerformed

    private void jrb_byLecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_byLecturerActionPerformed
        // TODO add your handling code here:
        jbt_searchRecord.setText("Search Lecturer");
        userOptions = "lecturer";
    }//GEN-LAST:event_jrb_byLecturerActionPerformed

    private void jrb_byNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_byNameActionPerformed
        // TODO add your handling code here:
        jbt_searchRecord.setText("Search Name");
        userOptions = "subjectName";
    }//GEN-LAST:event_jrb_byNameActionPerformed

    private void jbt_searchRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_searchRecordActionPerformed
        // TODO add your handling code here:
        String a = "";
            try {
                if(jtf_searchItems.getText().isEmpty()==false){
                
                    a = "SELECT \"subjectID\", \"subjectName\"FROM SUBJECT WHERE \""+userOptions+"\"='"+jtf_searchItems.getText()+"'";
                tableModel.setQuery(a);
                }
                else
                    JOptionPane.showMessageDialog(null,"Try to type in some detail so we can search it for you","USER INPUT REQUIRED", JOptionPane.WARNING_MESSAGE);
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);

            }
        
    }//GEN-LAST:event_jbt_searchRecordActionPerformed


    
    private void jbt_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_refreshActionPerformed
        // TODO add your handling code here:
        String a = "";
            try {
                a = "SELECT \"subjectID\", \"subjectName\" FROM SUBJECT";
                tableModel.setQuery(a);
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);

            }
    }//GEN-LAST:event_jbt_refreshActionPerformed

    private class WindowCloseListener extends WindowAdapter {

        @Override
        public void windowClosed(WindowEvent event) {
            tableModel.disconnectFromDatabase();
            System.exit(0);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbt_Enter;
    private javax.swing.JButton jbt_refresh;
    private javax.swing.JButton jbt_searchRecord;
    private javax.swing.JButton jbt_show_advance_options;
    private javax.swing.JRadioButton jrb_byCourseID;
    private javax.swing.JRadioButton jrb_byLecturer;
    private javax.swing.JRadioButton jrb_byName;
    private javax.swing.JTextField jtf_searchItems;
    private javax.swing.JLabel searchExaminerPanel_text_Search_by;
    private javax.swing.JPanel searchSubjectPanel_advancePanel;
    private javax.swing.JPanel searchSubjectPanel_leftPanel;
    private javax.swing.JPanel searchSubjectPanel_rightPanel;
    private java.awt.Label searchSubjectPanel_text_Record;
    private java.awt.Label searchSubjectPanel_text_Search;
    private java.awt.Label searchSubjectPanel_text_Subject;
    // End of variables declaration//GEN-END:variables
    private int switch_advanceSearch = 0;
    private subject subject;
    private MaintainExaminationSystem maintainExamSys = new MaintainExaminationSystem();
    static final String DATABASE_URL = "jdbc:derby://localhost:1527/f:/examinationSystemDB;create=true";
    static final String USERNAME = "taruc";
    static final String PASSWORD = "taruc";
    static final String DEFAULT_QUERY = "SELECT \"subjectID\", \"subjectName\" FROM SUBJECT";
    
    private ExaminerTableModel tableModel;
    private JTextField filterText = new JTextField();
    private String userOptions = "subjectID";
    private JScrollPane jpane = new JScrollPane(jTable1);
}
