package ui;

import java.awt.event.*;
import javax.swing.JOptionPane;
import domain.examiner;
import java.util.ArrayList;
import control.MaintainExaminationSystem;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tommy
 */
public class updateExaminer extends javax.swing.JPanel {

    /**
     * Creates new form createExaminer
     */
    private MaintainExaminationSystem maintainExamSys = new MaintainExaminationSystem();
    private examiner examiner;
    public updateExaminer(examiner examiner) {
        initComponents();
        this.examiner = examiner;
        ArrayList<String> courseList = new ArrayList<String>();
        for(int i=0;i<maintainExamSys.getCourseList().size();i++){
            courseList.add(maintainExamSys.getCourseList().get(i).getcourseName());
        }
        String[] courseArr = new String[courseList.size()];
        courseArr = courseList.toArray(courseArr);
        jcb_examiner_course.setModel(new javax.swing.DefaultComboBoxModel(courseArr));
        
        jcb_examiner_course.setSelectedItem(examiner.getexaminerCourse());
        jtf_examiner_name.setDocument(new updateExaminer.JTextFieldLimit(30));
        jtf_examiner_contactNum_back.setDocument(new updateExaminer.JTextFieldLimit(7));
        jtf_examiner_contactNum_front.setDocument(new updateExaminer.JTextFieldLimit(3));
        
        jtf_examiner_name.setText(examiner.getexaminerName());
        jtf_examiner_contactNum_front.setText(String.valueOf(examiner.getexaminerContactNumber().charAt(0))+String.valueOf(examiner.getexaminerContactNumber().charAt(1))+String.valueOf(examiner.getexaminerContactNumber().charAt(2)));
        jtf_examiner_contactNum_back.setText(String.valueOf(examiner.getexaminerContactNumber().charAt(4))+String.valueOf(examiner.getexaminerContactNumber().charAt(5))+String.valueOf(examiner.getexaminerContactNumber().charAt(6))+String.valueOf(examiner.getexaminerContactNumber().charAt(8))+String.valueOf(examiner.getexaminerContactNumber().charAt(9))+String.valueOf(examiner.getexaminerContactNumber().charAt(10))+String.valueOf(examiner.getexaminerContactNumber().charAt(11)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        createExaminerPanel_leftPanel = new javax.swing.JPanel();
        updateExaminerPanel_text_Create = new java.awt.Label();
        updateExaminerPanel_text_Record = new java.awt.Label();
        updateExaminerPanel_text_Examiner = new java.awt.Label();
        createExaminerPanel_rightPanel = new javax.swing.JPanel();
        updateExaminerPanel_text_Name = new java.awt.Label();
        updateExaminerPanel_text_Course = new java.awt.Label();
        jbt_resetField = new javax.swing.JButton();
        jbt_createExaminer = new javax.swing.JButton();
        jtf_examiner_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        updateExaminerPanel_text_Contact_number = new java.awt.Label();
        jtf_examiner_contactNum_front = new javax.swing.JTextField();
        jcb_examiner_course = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jtf_examiner_contactNum_back = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));

        createExaminerPanel_leftPanel.setBackground(new java.awt.Color(204, 204, 255));
        createExaminerPanel_leftPanel.setToolTipText("");

        updateExaminerPanel_text_Create.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        updateExaminerPanel_text_Create.setText("Update");

        updateExaminerPanel_text_Record.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        updateExaminerPanel_text_Record.setText("Record");

        updateExaminerPanel_text_Examiner.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        updateExaminerPanel_text_Examiner.setText("Examiner");

        javax.swing.GroupLayout createExaminerPanel_leftPanelLayout = new javax.swing.GroupLayout(createExaminerPanel_leftPanel);
        createExaminerPanel_leftPanel.setLayout(createExaminerPanel_leftPanelLayout);
        createExaminerPanel_leftPanelLayout.setHorizontalGroup(
            createExaminerPanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createExaminerPanel_leftPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(createExaminerPanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateExaminerPanel_text_Create, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateExaminerPanel_text_Examiner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateExaminerPanel_text_Record, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        createExaminerPanel_leftPanelLayout.setVerticalGroup(
            createExaminerPanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createExaminerPanel_leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateExaminerPanel_text_Create, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateExaminerPanel_text_Examiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateExaminerPanel_text_Record, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        createExaminerPanel_rightPanel.setBackground(new java.awt.Color(204, 255, 204));
        createExaminerPanel_rightPanel.setToolTipText("");

        updateExaminerPanel_text_Name.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        updateExaminerPanel_text_Name.setText("Name");

        updateExaminerPanel_text_Course.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        updateExaminerPanel_text_Course.setText("Course");

        jbt_resetField.setBackground(new java.awt.Color(255, 204, 153));
        jbt_resetField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_resetField.setText("Reset");
        jbt_resetField.setToolTipText("Click to reset all fields");
        jbt_resetField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_resetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_resetFieldActionPerformed(evt);
            }
        });

        jbt_createExaminer.setBackground(new java.awt.Color(255, 204, 153));
        jbt_createExaminer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_createExaminer.setText("Update");
        jbt_createExaminer.setToolTipText("Click to create record");
        jbt_createExaminer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_createExaminer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_createExaminerActionPerformed(evt);
            }
        });

        jtf_examiner_name.setBackground(new java.awt.Color(204, 204, 255));
        jtf_examiner_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_examiner_name.setToolTipText("Enter examiner's name here");

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setToolTipText("Bonjour");

        jLabel2.setToolTipText("Bonjour");

        updateExaminerPanel_text_Contact_number.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        updateExaminerPanel_text_Contact_number.setText("Contact number");

        jtf_examiner_contactNum_front.setBackground(new java.awt.Color(204, 204, 255));
        jtf_examiner_contactNum_front.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_examiner_contactNum_front.setToolTipText("Enter examiner's phone number");
        jtf_examiner_contactNum_front.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_examiner_contactNum_frontKeyTyped(evt);
            }
        });

        jcb_examiner_course.setBackground(new java.awt.Color(153, 255, 153));
        jcb_examiner_course.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcb_examiner_course.setModel(jcb_examiner_course.getModel());
        jcb_examiner_course.setToolTipText("Choos examiner's course");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("-");

        jtf_examiner_contactNum_back.setBackground(new java.awt.Color(204, 204, 255));
        jtf_examiner_contactNum_back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_examiner_contactNum_back.setToolTipText("Enter examiner's phone number");
        jtf_examiner_contactNum_back.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_examiner_contactNum_backKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout createExaminerPanel_rightPanelLayout = new javax.swing.GroupLayout(createExaminerPanel_rightPanel);
        createExaminerPanel_rightPanel.setLayout(createExaminerPanel_rightPanelLayout);
        createExaminerPanel_rightPanelLayout.setHorizontalGroup(
            createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbt_createExaminer, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_resetField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addComponent(updateExaminerPanel_text_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                        .addComponent(jtf_examiner_contactNum_front, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_examiner_contactNum_back, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtf_examiner_name, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcb_examiner_course, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 308, Short.MAX_VALUE))))
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateExaminerPanel_text_Course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateExaminerPanel_text_Contact_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        createExaminerPanel_rightPanelLayout.setVerticalGroup(
            createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateExaminerPanel_text_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_examiner_name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateExaminerPanel_text_Course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_examiner_course, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jtf_examiner_contactNum_back, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(210, 210, 210)
                                .addComponent(jLabel1))
                            .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                                .addGap(240, 240, 240)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbt_resetField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbt_createExaminer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(createExaminerPanel_rightPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateExaminerPanel_text_Contact_number, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(createExaminerPanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtf_examiner_contactNum_front, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)))
                        .addContainerGap(508, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(createExaminerPanel_leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createExaminerPanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(createExaminerPanel_leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(createExaminerPanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_resetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_resetFieldActionPerformed
        // TODO add your handling code here:
        int isConfirmed = 0;
        isConfirmed = JOptionPane.showConfirmDialog(null, "Are you sure you want to clear all fields?", "CLEAR FIELD CONFIRMATION", HEIGHT);
        if(isConfirmed==0){
            jtf_examiner_name.setText("");
            jtf_examiner_contactNum_front.setText("");
            jtf_examiner_contactNum_back.setText("");
            jcb_examiner_course.setSelectedIndex(0);
        }
        else{}
    }//GEN-LAST:event_jbt_resetFieldActionPerformed

    private void jbt_createExaminerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_createExaminerActionPerformed
        // TODO add your handling code here:
        if(jtf_examiner_contactNum_back.getText().length()==7&&jtf_examiner_contactNum_front.getText().length()==3&&jtf_examiner_name.getText().isEmpty()==false){

                int isConfirmed = 0;
            examiner.setexaminerName(jtf_examiner_name.getText());
            examiner.setexaminerContactNumber_front(jtf_examiner_contactNum_front.getText());
            examiner.setexaminerContactNumber_back(jtf_examiner_contactNum_back.getText());
            examiner.setexaminerCourse(String.valueOf(jcb_examiner_course.getSelectedItem()));
            examiner.setexaminerContactNumber();
            isConfirmed = JOptionPane.showConfirmDialog(null, "Are you sure you want to update this record with the following information:\nName: "+examiner.getexaminerName()+"\nCourse: "+examiner.getexaminerCourse()+"\nContact number: "+examiner.getexaminerContactNumber(), "UPDATE RECORD CONFIRMATION", HEIGHT);
            if(isConfirmed==0){ 
            if(examiner.getexaminerContactNumber_front().charAt(0)=='0'&&examiner.getexaminerContactNumber_front().charAt(1)=='1'){
                maintainExamSys.updateExaminer(examiner);
            JOptionPane.showMessageDialog(null, "Update record success!", "UPDATE RECORD SUCCESS", HEIGHT);
            }
            else
                JOptionPane.showMessageDialog(null, "Your phone number format is incorrect! (Tips: Phone number format: 01x-xxxxxxx)!", "CREATE RECORD FAIL", HEIGHT);
            
            }
            else{
                JOptionPane.showMessageDialog(null, "Update record fail!", "UPDATE RECORD FAIL", HEIGHT);
            }
            }
        else
            JOptionPane.showMessageDialog(null, "Update record fail! Please fill in all form before you decide to update record.", "UPDATE RECORD FAIL", HEIGHT);
    }//GEN-LAST:event_jbt_createExaminerActionPerformed

    private void jtf_examiner_contactNum_frontKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_examiner_contactNum_frontKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)){
           evt.consume();
           java.awt.Toolkit.getDefaultToolkit().beep();
       }
    }//GEN-LAST:event_jtf_examiner_contactNum_frontKeyTyped

    private void jtf_examiner_contactNum_backKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_examiner_contactNum_backKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
       if(!(Character.isDigit(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)){
           evt.consume();
           java.awt.Toolkit.getDefaultToolkit().beep();
       }
    }//GEN-LAST:event_jtf_examiner_contactNum_backKeyTyped

    
    public class JTextFieldLimit extends PlainDocument {
        private int limit;
        JTextFieldLimit(int limit) {
            super();
            this.limit = limit;
        }
        public void insertString( int offset, String  str, AttributeSet attr ) throws BadLocationException {
            if (str == null) return;
            
            if ((getLength() + str.length()) <= limit) {
                super.insertString(offset, str, attr);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel createExaminerPanel_leftPanel;
    private javax.swing.JPanel createExaminerPanel_rightPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbt_createExaminer;
    private javax.swing.JButton jbt_resetField;
    private javax.swing.JComboBox<String> jcb_examiner_course;
    private javax.swing.JTextField jtf_examiner_contactNum_back;
    private javax.swing.JTextField jtf_examiner_contactNum_front;
    private javax.swing.JTextField jtf_examiner_name;
    private java.awt.Label updateExaminerPanel_text_Contact_number;
    private java.awt.Label updateExaminerPanel_text_Course;
    private java.awt.Label updateExaminerPanel_text_Create;
    private java.awt.Label updateExaminerPanel_text_Examiner;
    private java.awt.Label updateExaminerPanel_text_Name;
    private java.awt.Label updateExaminerPanel_text_Record;
    // End of variables declaration//GEN-END:variables
}
