package ui;

import java.awt.event.*;
import control.MaintainExaminationSystem;
import domain.course;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tommy
 */
public class updateCourse extends javax.swing.JPanel {

    /**
     * Creates new form createExaminer
     */
    private MaintainExaminationSystem maintainExamSys = new MaintainExaminationSystem();
    private course course = new course();
    
    public updateCourse(course course) {
        initComponents();
        this.course = course;
        
        jtf_course_name.setDocument(new updateCourse.JTextFieldLimit(30));
        jtf_course_id.setDocument(new updateCourse.JTextFieldLimit(3));
        
        jtf_course_name.setText(course.getcourseName());
        jtf_course_id.setText(course.getcourseID());
        jta_course_description.setText(course.getcourseDescription());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        updateCoursePanel_leftPanel = new javax.swing.JPanel();
        updateCoursePanel_text_Update = new java.awt.Label();
        updateCoursePanel_text_Record = new java.awt.Label();
        updateCoursePanel_text_Course = new java.awt.Label();
        updateCoursePanel_rightPanel = new javax.swing.JPanel();
        updateCoursePanel_text_Course_name = new java.awt.Label();
        updateCoursePanel_text_Course_description = new java.awt.Label();
        jbt_resetField = new javax.swing.JButton();
        jbt_createCourse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_course_description = new javax.swing.JTextArea();
        jtf_course_name = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        updateCoursePanel_text_Course_id = new java.awt.Label();
        jtf_course_id = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 0, 0));

        updateCoursePanel_leftPanel.setBackground(new java.awt.Color(204, 204, 255));
        updateCoursePanel_leftPanel.setToolTipText("");

        updateCoursePanel_text_Update.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        updateCoursePanel_text_Update.setText("Update");

        updateCoursePanel_text_Record.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        updateCoursePanel_text_Record.setText("Record");

        updateCoursePanel_text_Course.setFont(new java.awt.Font("FangSong", 3, 48)); // NOI18N
        updateCoursePanel_text_Course.setText("Course");

        javax.swing.GroupLayout updateCoursePanel_leftPanelLayout = new javax.swing.GroupLayout(updateCoursePanel_leftPanel);
        updateCoursePanel_leftPanel.setLayout(updateCoursePanel_leftPanelLayout);
        updateCoursePanel_leftPanelLayout.setHorizontalGroup(
            updateCoursePanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateCoursePanel_leftPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(updateCoursePanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateCoursePanel_text_Update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateCoursePanel_text_Course, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateCoursePanel_text_Record, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        updateCoursePanel_leftPanelLayout.setVerticalGroup(
            updateCoursePanel_leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateCoursePanel_leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateCoursePanel_text_Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateCoursePanel_text_Course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateCoursePanel_text_Record, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(492, Short.MAX_VALUE))
        );

        updateCoursePanel_rightPanel.setBackground(new java.awt.Color(204, 255, 204));
        updateCoursePanel_rightPanel.setToolTipText("");

        updateCoursePanel_text_Course_name.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        updateCoursePanel_text_Course_name.setText("Name");

        updateCoursePanel_text_Course_description.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        updateCoursePanel_text_Course_description.setText("Description");

        jbt_resetField.setBackground(new java.awt.Color(255, 204, 153));
        jbt_resetField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_resetField.setText("Reset");
        jbt_resetField.setToolTipText("Click to reset all fields");
        jbt_resetField.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_resetField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_resetFieldActionPerformed(evt);
            }
        });

        jbt_createCourse.setBackground(new java.awt.Color(255, 204, 153));
        jbt_createCourse.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbt_createCourse.setText("Update");
        jbt_createCourse.setToolTipText("Click to create record");
        jbt_createCourse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbt_createCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_createCourseActionPerformed(evt);
            }
        });

        jta_course_description.setBackground(new java.awt.Color(204, 204, 255));
        jta_course_description.setColumns(20);
        jta_course_description.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jta_course_description.setRows(5);
        jta_course_description.setToolTipText("Enter examiner's home address");
        jScrollPane1.setViewportView(jta_course_description);

        jtf_course_name.setBackground(new java.awt.Color(204, 204, 255));
        jtf_course_name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_course_name.setToolTipText("Enter examiner's name here");

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setToolTipText("Bonjour");

        jLabel2.setToolTipText("Bonjour");

        updateCoursePanel_text_Course_id.setFont(new java.awt.Font("FangSong", 1, 24)); // NOI18N
        updateCoursePanel_text_Course_id.setText("Course ID");

        jtf_course_id.setBackground(new java.awt.Color(204, 204, 255));
        jtf_course_id.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtf_course_id.setToolTipText("Enter examiner's programe");
        jtf_course_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_course_idActionPerformed(evt);
            }
        });
        jtf_course_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtf_course_idKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout updateCoursePanel_rightPanelLayout = new javax.swing.GroupLayout(updateCoursePanel_rightPanel);
        updateCoursePanel_rightPanel.setLayout(updateCoursePanel_rightPanelLayout);
        updateCoursePanel_rightPanelLayout.setHorizontalGroup(
            updateCoursePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateCoursePanel_rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateCoursePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateCoursePanel_rightPanelLayout.createSequentialGroup()
                        .addComponent(jbt_createCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbt_resetField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(updateCoursePanel_rightPanelLayout.createSequentialGroup()
                        .addGroup(updateCoursePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(updateCoursePanel_rightPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(updateCoursePanel_rightPanelLayout.createSequentialGroup()
                                .addGroup(updateCoursePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updateCoursePanel_text_Course_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateCoursePanel_text_Course_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(updateCoursePanel_text_Course_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(updateCoursePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_course_name, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_course_id, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(663, Short.MAX_VALUE))))
        );
        updateCoursePanel_rightPanelLayout.setVerticalGroup(
            updateCoursePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateCoursePanel_rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updateCoursePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateCoursePanel_text_Course_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_course_name, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updateCoursePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateCoursePanel_rightPanelLayout.createSequentialGroup()
                        .addComponent(updateCoursePanel_text_Course_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(updateCoursePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(updateCoursePanel_rightPanelLayout.createSequentialGroup()
                                .addComponent(updateCoursePanel_text_Course_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(updateCoursePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(updateCoursePanel_rightPanelLayout.createSequentialGroup()
                                        .addGap(198, 198, 198)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(updateCoursePanel_rightPanelLayout.createSequentialGroup()
                                        .addGap(200, 200, 200)
                                        .addComponent(jLabel1)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(updateCoursePanel_rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbt_resetField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbt_createCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(updateCoursePanel_rightPanelLayout.createSequentialGroup()
                        .addComponent(jtf_course_id, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        updateCoursePanel_text_Course_description.getAccessibleContext().setAccessibleName("Intake year: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(updateCoursePanel_leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateCoursePanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(updateCoursePanel_leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(updateCoursePanel_rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_resetFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_resetFieldActionPerformed
        // TODO add your handling code here:
        int isConfirmed = 0;
        isConfirmed = JOptionPane.showConfirmDialog(null, "Are you sure you want to clear all fields?", "CLEAR FIELD CONFIRMATION", HEIGHT);
        if(isConfirmed==0){
            jtf_course_name.setText("");
            jta_course_description.setText("");
            jtf_course_id.setText("");
        }
        else{}
    }//GEN-LAST:event_jbt_resetFieldActionPerformed

    private void jbt_createCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_createCourseActionPerformed
        // TODO add your handling code here:
        if(jtf_course_id.getText().length()==3&&jtf_course_name.getText().isEmpty()==false&&jta_course_description.getText().isEmpty()==false){
            int isConfirmed = 0;
            course.setcourseName(jtf_course_name.getText());
            course.setcourseID(jtf_course_id.getText());
            course.setcourseDescription(jta_course_description.getText());
            isConfirmed = JOptionPane.showConfirmDialog(null, "Are you sure you want to update this record with the following information:\nName: "+course.getcourseName()+"\nCourse ID: "+course.getcourseID()+"\nCourse Description: "+course.getcourseDescription(), "UPDATE RECORD CONFIRMATION", HEIGHT);
            if(isConfirmed==0){
                    maintainExamSys.updateCourse(course);
            }
            else{
                JOptionPane.showMessageDialog(null, "Update record fail!", "UPDATE RECORD FAIL", HEIGHT);
            }
        }
        else
            JOptionPane.showMessageDialog(null, "Update record fail! Please fill in all form before you decide to update record.", "UPDATE RECORD FAIL", HEIGHT);
    }//GEN-LAST:event_jbt_createCourseActionPerformed

    private void jtf_course_idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_course_idKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isAlphabetic(c) || c==KeyEvent.VK_BACK_SPACE || c==KeyEvent.VK_DELETE)){
            evt.consume();
            java.awt.Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_jtf_course_idKeyTyped

    private void jtf_course_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_course_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_course_idActionPerformed

    public class JTextFieldLimit extends PlainDocument {
        private int limit;
        JTextFieldLimit(int limit) {
            super();
            this.limit = limit;
        }
        public void insertString( int offset, String  str, AttributeSet attr ) throws BadLocationException {
            if (str == null) return;
            
            if ((getLength() + str.length()) <= limit) {
                super.insertString(offset, str, attr);
            }
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbt_createCourse;
    private javax.swing.JButton jbt_resetField;
    private javax.swing.JTextArea jta_course_description;
    private javax.swing.JTextField jtf_course_id;
    private javax.swing.JTextField jtf_course_name;
    private javax.swing.JPanel updateCoursePanel_leftPanel;
    private javax.swing.JPanel updateCoursePanel_rightPanel;
    private java.awt.Label updateCoursePanel_text_Course;
    private java.awt.Label updateCoursePanel_text_Course_description;
    private java.awt.Label updateCoursePanel_text_Course_id;
    private java.awt.Label updateCoursePanel_text_Course_name;
    private java.awt.Label updateCoursePanel_text_Record;
    private java.awt.Label updateCoursePanel_text_Update;
    // End of variables declaration//GEN-END:variables
}
